weather-gov/weather.gov

src/grids.html, stress-test.sh
This adds some tinker code that pulls a list of approved observation stations for a WFO from the API and puts them on a map centered over Nashville. It's just here to get it out of my head, as a thought about what it means to display current conditions for a place.
Also adds a very basic stress testing script. It uses multiprocess curl to hit a target however many times specified. Coupled with `time`, it'll give us something to compare CMSes with. While this test doesn't tell us how well a CMS will perform in our production environment, it should give us good data about how they compare to each other.
=> Tinkering: a map view of current temperatures associated with a WFO

package-lock.json, package.json, src/index.html, src/lib/api/observations.js, src/lib/location.js, src/main.js, src/worker.js
- For current conditions, the UI now displays the location of the observation station providing the data plus the (rough) distance from the user's location to that observation station
- The `Observation` class was updated to also capture the lat/lng/altitude of the observation station and to add a helper function for computing the distance from the obs station to an arbitrary lat/lng. Altitude is currently ignored.
- The main page was updated to add a placeholder in the dom for the ob station location and distance
- If we decide to display distance to obs stations, we might want to see if we can get someone at the National Geodetic Survey (a NOAA office) to verify our approach is good enough. Basically, I've implemented the [Haversine distance …
=> Tinkering: Add observation station location and distance; some cacheing updates

.github/ISSUE_TEMPLATE/bug-template.md
Documenting bugs is a little different from documenting other work tasks.
This PR adds an issue template for documenting bugs.
=> Adds a new issue template for bugs

web/modules/weather_data/src/Service/WeatherDataService.php, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
The location we display in the current conditions is static for now. It currently points to Minneapolis. We want to switch it to Nashville.
- Changes the coordinates from downtown Minneapolis to downtown Nashville
- Modifies the Twig template to make wind speed/direction in the narrative text conditional, based on whether there is any wind.
=> For demo purposes, swtich to Nashville

.github/workflows/code-standards.yaml
Our tests currently do not run when added to a merge group, meaning they can never report success and will never successfully merge using merge queues.
This PR updates our tests to run when added to a merge group, enabling us to use merge queues.
=> Run tests in merge groups

.github/workflows/code-standards.yaml, .github/workflows/phpcs-problem-matcher.json, composer.json, composer.lock, docker-compose.yml, phpunit.xml, web/themes/new_weather_theme/src/StarterKit.php.test
We are not running automated tests in our CI/CD processes.
Adds unit tests to our CI/CD. We don't have any tests yet (and only very little PHP-testable code), so I added a test class for one of the generated classes. It just asserts that `1 = 1`, but it serves as a placeholder for what tests might look like.
Also fixes a bug in the phpcs step, where the output of phpcs was supposed to create GitHub annotations. I'd forgotten to copy over the annotation problem matcher when I switched us from [guix77/phpcs-drupal-action](https://github.com/guix77/phpcs-drupal-action).
And finally, I think this fixes a bug with how stuff was being cached. This new cacheing might be more aggressive, but that could mean saving on execution times.
=> Add phpunit tests

.github/workflows/code-review-templates/code-review-generic.md, .github/workflows/code-review-templates/code-review-web.md, .github/workflows/code-review.yaml
We want to use our code review checklists. This automatically posts the code review checklist on opened pull requests.
There are currently three PR checklists: 
* Generic (posted on every PR if conditions not met - no docs or web files were changed)
* Docs (posted if any docs files are changed but no web files are changed)
* Web, a full CR checklist (posted if any web files are changed)
Should we add documentation for this and if so where?
=> add a github action that automatically posts our code review template

web/modules/weather_data/src/Service/WeatherDataService.php
As described in #210, the short weather description should come from the descriptions in the API `/icons` endpoint, not from the text in the `/stations/[id]/observations` endpoint.
Closes #210
This PR builds on #208. It adds an additional mapping from the observation API icon name to condition text. It also creates a utility function to derive a conditions key from an observation rather than duplicating that code again.
=> Get weather description from icons description instead of current observations

.gitignore
When running `composer install` or `composer require`, there are additional drupal files loads. Those should come from the composer package.
Adds those files to our .gitignore.
=> Ignore more composer files.

Makefile, docs/dev/index.md
We have content exported with the single_content_sync (scs) module, but we don't have tools to make it easier to reimport (or even re-export).
This PR adds some Makefile targets:
- `export-content` will export all content using scs
- `import-content` will import content previously exported by scs
- `reset-site` will wipe the database and start over with a clean site install, configuration, and scs content, but does not touch the Drupal container
Additionally, the following Makefile targets were updated:
- `install-site` and `zap` will both now load scs content in addition to loading configuration
Lastly, this PR adds a new `docs/dev/index.md` document that contains getting-started info and a list of Makefile targets and what they do. This serves as the initial movement towards developer …
=> Add Make targets for importing/exporting content

.github/dependabot.yml, composer.lock, package-lock.json
We don't have automatic dependency scanning, so if our dependencies go out of date, we won't know it.
Enables GitHub Dependabot scanning. Daily for PHP dependencies, weekly for Javascript dependencies. And while I was here, I updated our dependencies.
We may also want to look into Snyk for both of these, but since that requires an account, I didn't want to create one myself. We'll need to make sure we at least vaguely understand how to hand off credentials at some point.
Part of #218.
=> Add dependency scanning

web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
The text color of the timestamp and "feels like" in the current conditions component are wrong. It's too light and doesn't have enough contrast.
Changes the text color to `text-gray-50`. Closes #199.
=> Fix current conditions timestamp and "feels like" text color

.github/pull_request_template.md
Current PR asks for more info than a requester needs.
This PR remove change type and checklist sections. It also adds instructional comments.
Compare this PR with new one https://github.com/weather-gov/weather.gov/blob/effea79ae1852b3b0baa92d7cfe11f88a65009fa/.github/pull_request_template.md
**before:**
**after:**
=> Pair down pull_request_template.md

Dockerfile.dev, Makefile
Sometimes we need to be able to dump and/or restore the database wholesale. Right now we have to do it by hand and it's difficult so we don't do it.
This PR adds Makefile commands for dumping and restoring the database. 
Dumps your current Drupal database to `web/config/database/dump.sql`. It is included in our `.gitignore` so it's not in this PR. Guess we'll share it privately if we need to.
Restores your `web/config/database/dump.sql` file to your Drupal database, replacing anything that is already there. You'll have to provide this file yourself, it's not in our git repo. 😛
=> Add helpers for dumping and restoring the database

web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_data/src/Service/WeatherDataService.php.test, web/modules/weather_data/weather_data.services.yml, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
- In the Twig template, runs translatable strings through the `t` filter.
- In the WeatherDataService, sends the current conditions text (e.g., "mostly sunny") through the translation manager
- I did this translation in the service because it is data from the API. Doing the translation in Twig would be funky because the current conditions text is a variable, so it would have to be double-translated, and that seemed dirty:
```php
{{ "The weather in @place is {{ $data["condition"] | t }}" | t }}
``` 
Also, ☝️ that doesn't work.
- Updates tests to inject a mock translation manager.
Closes #204
None, I guess. We don't actually have translations setup, so we can't be sure that this works as expected yet. But that'll come. I reckon for now we're just making sure the code makes sense.
=> Make the current conditions component translation-ready

web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_data/src/Service/WeatherDataService.php.test, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
The wind direction is displayed as degrees from north instead of the useful cardinal and ordinal names (north, northeast, etc.). See #301.
Sets the `direction` to a cardinal or ordinal name, adds `shortDirection` for the short version of the name, and moves the angle to an `angle` property.
Fixes #301.
=> Fix wind direction in the current conditions component

docs/dev/index.md
The "getting started" part of the dev docs is missing the step for setting up the `settings.dev.php` file.
Adds that step!
=> Add a missing step to the developer docs

web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_data/src/Service/WeatherDataService.php.test, web/modules/weather_data/src/Service/test_data/observation.bad-empty-icon.json, web/modules/weather_data/src/Service/test_data/observation.bad-null-icon.json
- Adds tests to cover the cases where the API returns null or an empty string for the icon of an observation
- Updates the weather data service to properly handle those cases.
Closes #333.
This one's pretty straightforward, I think.
=> Bug fix: catch when the icon is empty or null

Makefile, docs/dev/makefile.md
Should be able to run `make ci` or `make composer-install` to install any new dependencies in the composer.lock file.
The Makefile is a collection of commands that we regularly run in any environment, not just our local. `composer install` is one of them.
=> Add composer-install command to Makefile.

tests/e2e/cypress/e2e/location-pages-preserve-browser-history.cy.js, web/themes/new_weather_theme/assets/js/components/locationSearch.js
When Javascript sets `window.location` as a result of a direct user action, it results in pushing a new history state to the stack. When Javascript sets `window.location` without user interaction, it results in a history state *replacement* of the current state instead.
Our location search works kinda like this:
1. User types some stuff
2. We query ESRI geocoding API for list of matching place names
3. User selects an option
4. We query ESRI geocoding API for lat/long of the selected place
5. We change the `window.location` to `/point/{lat}/{long}`
Because step 5 is triggered by step 4 (ie, code rather than user interaction), we are replacing the current history state rather than pushing a new one.
This PR modifies the location search handler to explicitly push a new history state using …
=> Push URL on to the history stack before navigating away

.github/workflows/deploy-beta.yaml, .github/workflows/deploy-sandbox.yaml, .github/workflows/deploy-staging.yaml
Moves to using the [cloud-gov supported action](https://github.com/cloud-gov/cg-cli-tools) instead of the deprecated action. 
Will conduct a test of the sandbox script before merging.
=> move from using deprecated cg deploy to using the cloud-gov supported action

web/config/core.extension.yml
Removes the Drupal Internal Page Cache. This module aggressively caches pages sent to anonymous users, which doesn't work for us because our pages are highly dynamic. [Drupal's documentation](https://www.drupal.org/docs/administering-a-drupal-site/internal-page-cache) recommends disabling the module in this case, and it fixes the caching problem we've seen with the current conditions component.
Closes #370.
My [dev environment](https://weathergov-greg.app.cloud.gov/local/MPX/108/72/Minneapolis) has been running this branch for about 24 hours. You can see that the last updated time is within about an hour (consistent with what the API returns, and what appears on the existing point forecast), and I can attest that the temperature and conditions are accurate relative to what I see out my …
=> Disable internal page cache

web/themes/new_weather_theme/templates/layout/page--user.html.twig
This is a small piece of #306. When you log into Drupal, you are now dropped on to a page with a big button for creating a new weather story. Clicking it takes you directly to the correct place for that, so you don't have to click through the 3-4 levels of abstraction.
<details>
<summary>gif of logging in and seeing the new page</summary>
</details>
=> Provide a quick link to creating weather stories

web/themes/new_weather_theme/templates/layout/html.html.twig
USWDS does some DOM manipulation immediately when it loads, which disrupts the page loading order and forces the browser to start rendering prematurely. This PR adds the `defer` attribute to the USWDS Javascript so it doesn't run until after everything is ready so the browser isn't forced into a premature layout.
Closes #260
Compare:
- [Broken](https://weathergov-staging.app.cloud.gov/local/OHX/50/57/Nashville): The flash is very noticeable in Firefox, a little less so in Chrome. If you're using Firefox, it outputs a message to the console indicating that layout started prematurely.
- [Fixed](https://weathergov-greg.app.cloud.gov/local/OHX/50/57/Nashville): No flash, and in Firefox, no console message about premature layout.
=> Defer USWDS to prevent flash of unstyled content

web/modules/weather_blocks/src/Plugin/Block/DailyForecastBlock.php, web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php, web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php.test, web/modules/weather_data/src/Service/WeatherDataService.getDailyForecast.php.test, web/modules/weather_data/src/Service/WeatherDataService.getHourlyForecast.php.test, web/modules/weather_data/src/Service/WeatherDataService.php
Builds on #481 by making the rest of the weather data service behave the same as `getCurrentConditionsFromGrid`.
=> Refactor: Update remaining weather data service methods to accept grid parameters

.github/workflows/code-standards.yaml
Disables the test coverage reporter step of our code standards automated tests. This step is the one responsible for the extra comment on all our pull requests with the funky coverage histogram, which is a really odd way of presenting that data. It's not very useful and it creates extra notifications. Since we already have a step for enforcing a 90% lower-bound on code coverage, we don't really need this.
=> Remove test coverage reporter

web/modules/weather_data/src/Service/WeatherDataService.getDailyForecast.php.test, web/modules/weather_data/src/Service/WeatherDataService.getHourlyForecast.php.test, web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_data/src/Service/WeatherDataService.php.test, web/modules/weather_data/src/Service/legacyMapping.json, web/modules/weather_data/src/Service/test_data/daily.forecast.good.json, web/modules/weather_data/src/Service/test_data/observation.bad-empty-icon.json, web/modules/weather_data/src/Service/test_data/observation.bad-null-icon.json, web/modules/weather_data/src/Service/test_data/observation.good-both.json, web/modules/weather_data/src/Service/test_data/observation.good-heatindex.json, web/modules/weather_data/src/Service/test_data/observation.good-no-feelslike.json, web/modules/weather_data/src/Service/test_data/observation.good-windchill.json
We currently key off the icon returned by the API to map into a condition description. However, (we think) we should be using the text from the API. This PR updates the current conditions, hourly forecast, and daily forecast components to use the text provided by the API.
Addresses #455 
A simple cache clear should have this ready to run locally.
I think it would be good to do a design/eng huddle to look at this together. It would also still be super helpful to have a complete and definitive list of text values the API may return so we know what kind of text lengths we need to accommodate.
=> Use API text for conditions descriptions

scripts/post-deploy.sh
The content we store in our repo is mostly just to get a representative site stood up quickly. Now that our deployed environments are up, we no longer need to import this content into them.
=> No longer import content on deployments

web/themes/new_weather_theme/assets/js/components/locationSearch.js, web/themes/new_weather_theme/templates/block/block--weathergov-location-search.html.twig
Adds a button users can click to use their browser's geolocation feature instead of typing in a location. The behavior is roughly as follows:
The idea is if the user has not already given us permission, we will first let them know we're going to ask for it and disclose how we'll use that information. Then we ask the browser, which will usually generate a browser-supplied prompt to allow/prevent.
Closes #184 
`make cc` should do the job.
<details>
<summary>The location search component gets a new button:</summary>
</details>
<details>
<summary>The prompt if the user has not previously given us permission to use location:</summary>
</details>
=> Add an option for users to use their browser's geolocation feature

.github/workflows/code-standards.yaml, .gitignore, tests/e2e/cypress/e2e/screenshots.cy.js
I don't think this is useful unless we can integrate the newly-captured screenshots into our review process. Ideally I think we'd want the screenshots to be added to a comment that gets updated on each push (instead of new comments each time). GitHub doesn't provide an API for uploading images into comments, so we'll have to dance around that a little bit. There are existing actions that do it, but they add new comments each time, so that'd be noisy.
Adds an additional test to our end-to-end tests that iterates over a list of pages we want to screen shot and gets screen shots of all of those pages at phone, table, and desktop viewport widths.
Nothing much. Running end-to-end tests will create screenshots (in the git-ignored) `tests/e2e/cypress/screenshots/screenshots.cy.js/` directory.
=> Add screenshots to our end-to-end tests

web/themes/new_weather_theme/templates/block/block--system-branding-block.html.twig
Previously, each part of the site branding (logo, title, slogan) was wrapping its own link. Now we wrap the entire branding component in a single hyperlink, while also giving it good flex layout properties and structure.
This PR addresses the first item of #516 
We should double check about any accessibility / screenreader implications.
Also look closely, as some of the alignment of items has changed due to updating the flexbox structure of the elements. We can always adjust to make this more like the current version if needed.
<details><summary>Before:</summary>
</details>
<details><summary>After:</summary>
</details>
=> Site branding header styling / structure

web/config/block.block.new_weather_theme_currentconditionsblock.yml, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
Per one of the items in #516, the current conditions block does not have an h2 header. This prevents good screen reader navigation.
We have added the header -- and the config values that tell the block to display its label -- in this PR. Additionally, the header element has the `usa-sr-only` attribute, **which means it will be invisible but will still be captured by the screen reader**. We've done this in order to preserve the original design.
In this screenshot, you'll see the accessibility inspector highlighting an invisible element to the left (it's small). The inspector shows that it is a heading with the text Current conditions
=> Current conditions header

Makefile
Enabling Twig debugging causes it to add HTML comments to the markdown that tell you what templates it is searching for along the way, which is super helpful for figuring out what a new template should be named.
Disabling the markup cache means that any change to a template file will be rendered immediately so you do not need to manually clear the cache. You'll still need to clear the cache for module changes.
`make import-config` will get this change configured. Thereafter, `zap` and `reset-site` will also do it. These two settings are ***NOT*** included in exported configurations, so there's no risk of accidentally pushing them into production.
=> Enable Twig debugging and disable markup caching in dev

phpunit.xml, web/config/block.block.weathergov_admin_breadcrumbs.yml, web/config/block.block.weathergov_admin_help.yml, web/config/block.block.weathergov_admin_mainpagecontent.yml, web/config/block.block.weathergov_admin_messages.yml, web/config/block.block.weathergov_admin_pagetitle.yml, web/config/block.block.weathergov_admin_primaryadminactions.yml, web/config/block.block.weathergov_admin_tabs.yml, web/config/block.block.weathergov_admin_tabs_2.yml, web/config/core.entity_form_display.node.weather_narrative.default.yml, web/config/core.entity_view_display.node.weather_narrative.default.yml, web/config/core.extension.yml, web/config/field.field.node.weather_conditional.body.yml, web/config/field.field.node.weather_narrative.body.yml, web/config/system.action.user_add_role_action.forecaster.yml, web/config/system.action.user_remove_role_action.forecaster.yml, web/config/system.theme.yml, web/config/user.role.forecaster.yml, web/themes/new_weather_theme/new_weather_theme.info.yml, web/themes/new_weather_theme/tests/new_weather_theme.theme.php.test, web/themes/weathergov_admin/tests/weathergov_admin.theme.php.test, web/themes/weathergov_admin/weathergov_admin.info.yml, web/themes/weathergov_admin/weathergov_admin.theme
* Adds a new admin theme that derives from the Claro theme (our current default)
* Sets the admin theme to our new one
* Adds a hook to our new theme to remove the menu configuration and revision information panels from the weather narrative creation page
* Updates the content type configuration to hide additional fields:
* "Published" checkbox - it will just always be enabled for now (scheduling will be a separate body of work)
* Tags
* URL aliases
* Front-page promotion
* Authoring information (we will derive this from the logged-in user)
* Limits the body input type to basic HTML, so there's no dropdown box for users to choose their type
You'll need to import config. That should be it.
=> Hide unnecessary fields in the weather narrative content type

web/modules/weather_routes/src/Controller/LocationAndGridRouteController.php
This PR serves as a general purpose stopgap for #517. If any latitude/longitude (taken from search) does not return a grid cell, it redirects to `/not-implemented`. We will need to add content in each environment at that location, but in the meantime it'll at least result in a 404.
It also logs each time this happens so we'll be able to determine if it's happening anywhere else, though that seems unlikely. (Except for the part where a lat/long may be outside of NWS's grids entirely, but we haven't addressed that yet.)
closes #532
https://github.com/weather-gov/weather.gov/assets/142943695/d78ffaf4-f6c4-44e9-bf3f-8b47c0257556
=> If a given latitude and longitude does not produce a grid, show a "not implemented page

web/themes/new_weather_theme/templates/block/block--weathergov-daily-forecast.html.twig, web/themes/new_weather_theme/templates/navigation/menu--footer.html.twig
This PR deals with two remaining accessibility concerns highlighted in #516 :
You will want to use VoiceOver to test the following:
- That the links in the footer are labelled only as "footer primary links"
- That the daily forecast temperature text items are read as a complete sentence, and that the individual number and degrees texts are not read (separately) at all
=> Remaining accessibility fixes

web/config/user.role.forecaster.yml
Adds permissions for the Forecaster role, such that the admin theme will load (ie, when editing or creating content, there is appropriate styling and the correct theme loads)
When editing content as a user who is a Forecaster, you should **not** see any unstyled content.
=> Forecaster can use admin theme

web/modules/weather_blocks/src/Plugin/Block/CurrentConditionsBlock.php, web/modules/weather_blocks/src/Plugin/Block/CurrentConditionsBlock.php.test, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
- Fixes a bug where the narrative text in the current conditions component did not include the place name anymore. (Broken in #501)
- Adds "feels like" temperature to the narrative text
- Hides the widget-like display from screen readers and skips straight to the narrative text.
=> Fix-up current conditions for screen readers

web/config/block.block.new_weather_theme_localalertsblock.yml, web/modules/weather_blocks/src/Plugin/Block/LocalAlertsBlock.php, web/modules/weather_blocks/src/Plugin/Block/LocalAlertsBlock.php.test, web/modules/weather_data/src/Service/Test/WeatherAlertTrait.php.test, web/modules/weather_data/src/Service/Test/test_data/alerts.good.json, web/modules/weather_data/src/Service/WeatherAlertTrait.php, web/modules/weather_data/src/Service/WeatherDataService.php, web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
Very roughly puts alerts on the location page. These haven't been styled according to designs, they're just USWDS alerts plopped on the page, to show that we can get them.
The alerts from the API come in a few different configurations, but the biggest issue I think we'll run into in the short term is the description text. In some cases, the text is ***only*** the "what/when/where/impacts" bits. Other times, those bits are missing entirely and the description is some other blurb. I suspect there are cases where the description is both at once. This PR does not attempt to address all of those cases, though it makes a first pass at pulling out the what/when/where/impacts statements if it can.
Closes #522.
```
make cc
make import-config
```
It may also want a `make rebuild`, but that …
=> Fetch hazards for a location and put them on the page

package.json, tests/e2e/cypress/e2e/invalid-locations-are-not-found.cy.js, web/modules/weather_blocks/src/Plugin/Block/WeatherBlockBase.php, web/modules/weather_blocks/src/Plugin/Block/WeatherBlockBase.php.test
- Fixes the logic to determine whether or not a block has been configured by checking for both `false` and the default value `,,`.
- Closes #572
- Adds end-to-end tests to catch the bug
- Adds unit tests to catch the bug
=> Fix a bug with how blocks determine if they are configured

web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
Remove the `<h4>` element from the prototype alert component and replaces it with an h4-styled paragraph element. This fixes the heading ordering.
Closes #599 
`make cc`
=> replace h4 with h4-styled paragraph

web/modules/weather_data/src/Service/Test/TryParsingDescriptionText.php.test, web/modules/weather_data/src/Service/Test/WeatherAlertTrait.php.test, web/modules/weather_data/src/Service/WeatherAlertTrait.php, web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
This PR implements the changes requested in #592
After some messing around with USWDS grid options, we determined the best choice was to use an inline `columns:2` style string on the unordered list.
=> Weather alert area description formatting

web/themes/new_weather_theme/templates/block/block--weathergov-local-alert-list.html.twig, web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
This PR implements the changes requested in #657, primarily the use of USWDS accordions for the hazard alert information.
We have also adjusted the styling according to the ticket.
The first alert accordion will be open and the others should be closed.
<details>
<summary>Example:</summary>
</details>
=> Hazard accordion styling

web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
#666 identified a couple of issues, one of which is that the alert description seemed to be displaying twice. This PR removes the duplicate display.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
=> Remove dupe of alert description

.github/workflows/code-standards.yaml, Dockerfile.dev, composer.json, composer.lock, web/modules/README.txt, web/themes/README.txt
This updates our modules with dependencies in Drupal Core to 10.2 as recommended for security and feature updates. It also updates to a compatible Drush. There is one change that needed to be made to xdebug - it needs to be downgraded since there is a known issue with 10.2. See https://git.drupalcode.org/project/drupal/-/merge_requests/5774
=> update drupal core

package.json
We keep our contributors list in the root `package.json` file, but we haven't updated it in a while. This PR adds our deputy product owner @coreypieper and friend-of-the-show @elijah-wright.
Also adds @partly-igor, @eric-gade, and @loganmcdonald-noaa, team members who cycled in a while back. Goes to show just how long it's been since we've updated this thing.
If any of you would rather not be included in the list, just let me know and I'll update it.
=> Update our list of contributors

tests/api/data/gridpoints/TST/1,1/forecast.json
The test daily forecast data doesn't have enough time periods to cover every case, so sometimes the last day in the extended forecast only shows a high or low temperature but not both. This adds another period so that doesn't happen. Basically this test data fix is so we don't think there's a bug where there isn't. 😛
=> Add an extra time period to our daily forecast test data

web/modules/weather_blocks/src/Plugin/Block/CurrentConditionsBlock.php, web/modules/weather_blocks/src/Plugin/Block/DailyForecastBlock.php, web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php, web/modules/weather_blocks/src/Plugin/Block/LocalAlertListBlock.php, web/modules/weather_blocks/src/Plugin/Block/LocalAlertsBlock.php, web/modules/weather_blocks/src/Plugin/Block/LocationSearchBlock.php, web/modules/weather_data/src/Service/WeatherDataService.php, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig, web/themes/new_weather_theme/templates/block/block--weathergov-daily-forecast.html.twig, web/themes/new_weather_theme/templates/block/block--weathergov-hourly-forecast.html.twig, web/themes/new_weather_theme/templates/partials/uswds-alert.html.twig
- Updates the weather data service to cache exceptions if an API endpoint fails after backoff-retries, so other blocks won't waste time trying the same thing.
- Updates all of our blocks that use API data to catch exceptions and send back an `error` boolean
- Adds a USWDS alert partial
- Updates the blocks' twig templates to show a USWDS alert partial if there is an error
closes #651
`make cc` and *maybe* `make rebuild`, because as ever, I'm not sure what's necessary to get PHP changes to take effect.
=> Basic error handling in weather blocks

web/modules/weather_blocks/weather_blocks.module, web/themes/new_weather_theme/templates/layout/html.html.twig
Implements the `template_preprocess_default_variables_alter` hook to inject some of our own globals. We can add to this later as-needed, but for now, our globals object looks like this:
```
{
alerts: <bool; default false>,
place: <bool|string; default false>
}
```
Then we can use those in any of our twig templates with `{{ weather.alerts }}` or `{{ weather.place }}`. This PR also adds the location page place name to the page title using this global data.
I don't think we can do dependency injection on these module-level hook handlers, so it's a little messy and... perhaps untestable? Not thrilled about that but I mean... I suspect we're already testing a lot more than most Drupal sites.
`make rebuild && make cc`
=> Add global template data

manifests/manifest-beta.yaml, manifests/manifest-eric.yaml, manifests/manifest-greg.yaml, manifests/manifest-staging.yaml, manifests/manifest.template.yaml
Since we started installing new relic on boot we need some more memory. This recently caused a deploy of beta to fail.
=> bump memory in all environments

tests/e2e/cypress/e2e/tabbed-nav.cy.js, web/themes/new_weather_theme/templates/layout/page--local.html.twig
As a follow on to the tabbed-nav work and in addressing to #729, this PR ensures that the "Alerts" tab is only rendered on location pages that actually have alerts.
`make cc` should do the trick. Note that we are using the recorded demo endpoints for sample data of with/without alerts.
<details>
<summary>No alerts</summary>
</details>
<details>
<summary>With alerts</summary>
</details>
=> Conditionally rendering the alerts tab and tab area

.eslintrc.js, .gitattributes, .gitignore, Makefile, docker-compose.yml, docs/dev/index.md, docs/dev/spatial-data.md, load-shapefiles.js, package-lock.json, package.json, scripts/load-spatial-data.sh, spatial-data/Dockerfile.spatial, spatial-data/c_05mr24.dbf, spatial-data/c_05mr24.prj, spatial-data/c_05mr24.shp, spatial-data/c_05mr24.shx, spatial-data/cities500.txt, spatial-data/load-shapefiles.js, spatial-data/package-lock.json, spatial-data/package.json, spatial-data/s_05mr24.dbf, spatial-data/s_05mr24.prj, spatial-data/s_05mr24.shp, spatial-data/s_05mr24.shx
* Adds scripts and documentation for loading geospatial data locally and in cloud environments.
* Adds our current geospatial data sources as git LFS files
closes #723
=> Load spatial data

tests/a11y/cypress/support/e2e.js, tests/e2e/cypress/support/e2e.js, tests/load-times/cypress.config.js, tests/load-times/cypress/support/e2e.js, web/themes/new_weather_theme/new_weather_theme.info.yml, web/themes/new_weather_theme/new_weather_theme.libraries.yml
Adds the DAP script to all of our pages.
Question for @shadkeene! The [DAP implementation guide](https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20DAP%20Code%20Capabilities%20Summary%20and%20Reference.pdf) lists some configurations we must and can set. I only set the two listed below, but if you want to add more (or change the ones I've put in), it's easy to change now and in the future.
* agency: `NOAA`
* subagency: `NWS`
* sitetopic: `weather,safey`
Closes #682
=> Add DAP to pages

docs/dev/intercepting-the-api.md, tests/api/config.js, tests/api/local.js, tests/api/main.js, tests/api/package-lock.json, tests/api/package.json, tests/api/proxy.js, tests/api/save.js, web/modules/weather_data/src/Service/WeatherDataService.php
The API proxy server now has an endpoint at [localhost:8081/bundle](http://localhost:8081/bundle) that will enable capturing a "bundle" of API responses associated with the same page load. The result is a ZIP file that we can share more easily. Just unzip it locally and then visit the same location page that generated the bundle. (You may have to clear your Drupal cache first, or wait a minute or so for them to expire.)
Also adds a header to our outgoing API requests identifying the Drupal response we're servicing. That's necessary for the whole "bundling" thing, but we might other uses for it in the future. It's not a personal identifier – it's based on the current time.
=> Add a `/bundle` endpoint to fully capture all the API data in a single page load

package-lock.json, package.json, tests/e2e/cypress/e2e/tabbed-nav.cy.js, tests/e2e/cypress/support/e2e.js, web/themes/new_weather_theme/assets/js/components/TabbedNavigator.js, web/themes/new_weather_theme/templates/layout/page--local.html.twig
This PR addresses #733 by adding the expected accessibility behavior and attributes as [recommended by the W3C per these guidelines](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-manual/).
Appropriate ARIA attributes and relationships have been added where needed, and we've added a few e2e tests to make sure the navigation that W3C recommends is implemented properly. Specific nav things to look out for:
* If a tab is in focus, pressing the `Tab` key __should not__ move to the next tab button, but rather put the focus into the corresponding tabpanel (ie the tab's content container).
* Left/right arrow keys are used to put the focus on the next or previous tab button, if a tab button is currently in focus (instead of the `Tab` key, see above)
* Left/right arrows that go too …
=> Tabbed navigation a11y fixes

Dockerfile.dev
Something in the composer 2.7 release changed how directories get created. The 2.2 release line is LTS, though, so we should probably be pinning to that anyway. This PR makes that pin.
It also updates the `DRUPAL_VERSION` environment variable we set to be the right Drupal version. Oops.
=> Pin our composer version to LTS, not just latest 2.x

tests/api/data/testing/gridpoints/BMX/59,84.json, tests/api/data/testing/gridpoints/FGZ/74,89.json, tests/api/data/testing/gridpoints/LZK/83,73.json, tests/api/serve.js, tests/pages.json, web/modules/weather_blocks/src/Plugin/Block/HourlyPrecipitationBlock.php, web/modules/weather_data/src/Service/Test/GetHourlyPrecipitation.php.test, web/modules/weather_data/src/Service/UnitConversionTrait.php, web/modules/weather_data/src/Service/WeatherDataService.php, web/themes/new_weather_theme/templates/block/block--weathergov-hourly-forecast.html.twig, web/themes/new_weather_theme/templates/block/block--weathergov-hourly-precipitation.html.twig, web/themes/new_weather_theme/templates/block/block--weathergov-weather-story.html.twig, web/themes/new_weather_theme/templates/layout/page--point.html.twig
- adds a `getHourlyPrecipitation` method to the data service, using the `/gridpoints/{wfo}/{x},{y}` endpoint
- adds an hourly precipitation block that puts the next 3 6-hour chunks of precipitation into a table
- the first of these chunks may actually start in the past; I filter out the ones that ***end*** in the past
- removes the "hourly forecast" heading from the hourly forecast block and puts it in the page template, since where it sits may be independent of the hourly forecast block
- adds the hourly precipitation block to the today tab
> [!NOTE]  
> It might be worth holding this one until there's meaningful rain in someone's forecast so we can double-check that it's working? I feel good about it with the tests, but it'd be nice to see it working in the real world.
closes #796
=> Show hourly (or six-hourly... whatevs) precipitation amounts

web/modules/weather_data/src/Service/AlertPriority.php
Snow Squall Warning is a fairly new alert type. It is present in our prioritized list of hazards but it is not included in the list of land hazards. This PR adds it.
=> Add snow squall warning to land hazards

tests/api/save.js, tests/api/serve.js
When we record bundles, we currently capture the data exactly as provided by the API. As a result, data in bundles can slowly become outdated and no longer displayed by the site. This PR updates timestamps as it records them so that we preserve the relative time from "now" instead of an absolute time. This way, when we replay a bundle, the data presented should be identical to when it was captured, regardless of when it's played back (except for the timestamps, of course, which will be computed as a time relative to when the page is loaded).
=> When saving bundles, save API times as relative to the time the bundle is captured

manifests/manifest-design.yaml, tests/api/main.js, tests/api/manifest.yml, tests/api/package-lock.json, tests/api/package.json
This deploys our api proxy endpoints for playing and stopping bundles to cloud.gov (https://weathergov-api-proxy.app.cloud.gov/play/testing). This allows us to use bundles creating locally to fake data in cloud.gov which is useful for showing off certain behavior during tests or to each other. Pretty neat! Thank you @greg-does-weather!
We've removed the endpoint for creating bundles so this can only be used to play or stop bundles that have been previously created. It will take coordination between design and engineering to create new bundles for desired scenarios. 
We had previously talked about making this an internal link between our two cloud.gov accounts but don't see a threat model for interaction with the api proxy at this point, and we would like to keep the UI. This is only …
=> Setup the api proxy to work in cloud.gov

.github/workflows/update-theme-libraries.yaml
Fixes the check added in #788. As @elijah-wright pointed out then, we wanted to check for a zero status, not non-zero ones. To you, Elijah:
The comments in this PR are out of whack because I squashed down to just one commit. But if you want to see it working correctly yourself, change one of our CSS or JS assets on this branch and push it. You'll get the comment from the bot. Then update the libraries file and note that you don't get another comment.
=> Fix the library version checker thing

Makefile, web/modules/weather_blocks/src/Plugin/Block/CurrentConditionsBlock.php, web/modules/weather_data/src/Service/NewRelicMetrics.php, web/modules/weather_data/src/Service/Test/Base.php, web/modules/weather_data/src/Service/Test/GetCurrentConditionsFromGrid.php.test, web/modules/weather_data/src/Service/Test/GetObsDistanceInfo.php.test, web/modules/weather_data/src/Service/Test/LogObservationDistanceInfo.php.test, web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_data/weather_data.services.yml, web/modules/weather_routes/src/Controller/LocationAndGridRouteController.php, web/sites/default/settings.cloudgov.php, web/sites/default/settings.php
This PR, in part, implements the logging features outlined in #765 . It also implements additional changes we determined were needed as we went along, in particular the use of NewRelic as the logging endpoint for these distance metrics.
To summarize the primary task in the ticket: we want to log the number of stations a user had to cycle through until getting to a "valid" observation station, and to also log the distance from the user to that valid observation station.
Until we merge in the [point url PR](https://github.com/weather-gov/weather.gov/pull/769), we will not have a reliable point to measure from when getting the distance to the observation station. Instead, this PR implements a workaround: we take the WFO grid cell geometry, find the closest point in that geometry to the …
=> Observation distance logging with NewRelic

.github/workflows/code-standards.yaml
* Disable the >=90% code coverage requirement. This is a PR to satisfy [issue 838](https://github.com/weather-gov/weather.gov/issues/838)
* In the future, PR can be reverted easily for ticket 844
* See below github test suite proving that 90% coverage test has been disabled
=> 838 / Remove 90% test coverage requirement from github

web/modules/weather_data/src/Service/ObservationsTrait.php, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
When the wind speed is 0, we display `N/A`. That is incorrect. PHP thinks `null` and `zero` are equal. This PR adds strict equality checking to fix that bug.
[reference](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1710347151677179)
=> Fix wind speed display when the value is zero.

tests/api/config.js
This way when we redeploy, or the proxy restarts for some reason, it will restart by serving the R3 bundle.
=> Have the API proxy default to serving the R3 bundle when it starts up

web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
When working on #894 I realized there was some unnecessary padding classes that were cancelling each other out in the alert tab. Quick fix to simplify. Visually should look the same as before.
=> Remove unnecessary padding in alert tab

web/modules/weather_data/src/Service/DataLayer.php
Adds the logger trait to the data layer. The bug is currently active in staging, the result being that we can't see current conditions or any forecast data for any location.
=> CRITICAL: Fixes a bug where all data requests fail

web/modules/weather_blocks/src/Plugin/Block/DailyForecastBlock.php, web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php, web/modules/weather_blocks/weather_blocks.module, web/modules/weather_data/src/Service/AlertTrait.php, web/modules/weather_data/src/Service/DailyForecastTrait.php, web/modules/weather_data/src/Service/ObservationsTrait.php
We removed some code that converted point arrays (`[lon, lat]`) into objects (`{ lat: y, lon: x }`), but not all of the code that uses these coordinates was updated. In dev, this does not present any errors, but in our cloud environments it causes SQL errors.
=> CRITICAL: Fix an issue with point lat/lon

tests/api/data/R3/alerts/active__status=actual&area=MT.json
One of the R3 alerts has a small bug where the end date is before the start date. The correct end date should be 5 AM MT Wed, 2/26. 
Question – Do we need to redeploy the proxy only? Everything?
=> R3 fix date 

web/modules/weather_data/src/Service/ObservationsTrait.php, web/modules/weather_data/src/Service/UnitConversion.php
Null is equal to zero and false, but that's pretty much never what we actually want. Change our null equality checks to strict equality.
Incidentally fixes #912
=> Strict comparisons on null

web/modules/weather_blocks/src/Plugin/Block/WeatherBlockBase.php, web/modules/weather_blocks/weather_blocks.module, web/modules/weather_data/src/Service/AlertTrait.php, web/modules/weather_data/src/Service/DailyForecastTrait.php, web/modules/weather_data/src/Service/DataLayer.php, web/modules/weather_data/src/Service/ObservationsTrait.php, web/modules/weather_data/src/Service/SpatialUtility.php, web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_routes/src/Controller/LocationAndGridRouteController.php
It seems silly to have code sprinkled across several places for building SQL-ready representations of geometries. It also seems silly to have to remember that in a point array, longitude comes first and latitude second. So this PR switches all of our points to objects with `lat` and `lon` properties so we can be more explicit, and adds utilities for simplifying stuff.
* Adds a SpatialUtility class for putting spatial stuff in one place
* converts an array of lat/lon to a single point object with lat/lon properties
* converts an array of point arrays into an array of point objects
* creates SQL-query-ready WKT representations of geometries and points
* Modifies a bunch of code to use the utility classes
* Switches point arrays to point objects for readability
* Fixes an uncaught exception …
=> Handle lat/lon consistently

web/themes/new_weather_theme/templates/block/block--weathergov-location-search.html.twig, web/themes/new_weather_theme/templates/layout/footer.html.twig, web/themes/new_weather_theme/templates/layout/html.html.twig
Adds the Touchpoints script. If we should be using a different form, we'll need to update this URL. Here's the form I created, with @sarahmhgov and I as form managers:
https://touchpoints.app.cloud.gov/admin/forms/22acf675
closes #913
- I used the "blue button and modal" option. We don't have much control over the button except for the text. It shows up at the far bottom right. Is that okay, or should we use one of the other options?
=> Add touchpoints

web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/HourlyForecast/Alerts.php.test, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig, web/themes/new_weather_theme/templates/partials/daily-high-low.html.twig, web/themes/new_weather_theme/templates/partials/hourly-table.html.twig
- Where we display degrees, visually use two characters so they will be in our design system fonts, but hide those from screen readers
- For screen readers, preserve the single character and mark it sr-only
closes #930
=> For visual cases, use separate degree and F characters

composer.json, composer.lock, tests/e2e/cypress/e2e/hourly-forecast-table.cy.js, web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/Alerts/Alerts.php.test, web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/HourlyForecast/Alerts.php.test, web/modules/weather_data/src/Service/AlertUtility.php, web/modules/weather_data/src/Service/Test/AlertUtility.php.test, web/modules/weather_data/src/Service/Test/LegacyIconMapping.php.test
- Sort currently-active alerts by priority
- Sort future alerts by onset time
- If multiple alerts have the same onset time, sort them by priority within their onset time
closes #940
- Incidentally updates the alert structure tests to use JSON schema validation, so we don't have to care as much about *actual* values, only the form of the values. (Both of those e2e tests needed to be updated for this PR anyway because the ordering of alerts was different after the change, and I figured rather than keep fighting these super fragile timing tests, I'd just... try something new.)
=> Change alert ordering

web/themes/new_weather_theme/templates/block/block--weathergov-dynamic-safety-information.html.twig, web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig, web/themes/new_weather_theme/templates/layout/page--point.html.twig
This PR moves the "Tips to Stay Safe" section for each hazard into it's corresponding accordion. It removes the title from hazards that don't have any dynamic safety content written yet. 
Closes #931 and #970 
Hazard with dynamic safety content
Hazard without dynamic safety content
=> Move Tips to Stay Safe inside accordion

web/config/cloudgov/samlauth.authentication.yml, web/config/sync/block.block.new_weather_theme_locationsearchblock.yml, web/themes/new_weather_theme/new_weather_theme.theme
Currently deployed to https://weathergov-greg.app.cloud.gov/, see https://weathergov-greg.app.cloud.gov/user/login to start. 
Following #952 this PR: 
* Upon logging into the CMS, lands the user immediately on the workbench OOTB dashboard (most recent content that you engaged with)
* Once logged in, user is still be able to access the front-facing site in a separate tab or window
* Upon logging out of the CMS, have the option on that logout page (/user/login) to log back in
Login/logout page (at /user or /user/login when logged out): 
Logout button (unchanged):
=> Login & logout flows

.github/actions/setup-site/action.yml, .github/workflows/code-standards.yaml
- caches a dump of our fully-populated database (keyed on config and content hashes)
- if no cache, builds the database
- in subsequent testing steps, rather than building the database, restore it from cache
This takes our build times from around 8 minutes to around 4 minutes.
=> Cache a database dump in CI/CD to speed up runs

tests/a11y/cypress/e2e/dates-are-localized.cy.js, web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
The timestamp in the screen reader narrative section of the current conditions component did not get updated when we switched how we do time localization. This PR fixes that.
> [!NOTE]  
> VoiceOver treats inline elements (like `span` or `time`) as independent blocks when reading them, so users must navigate to them individually. We cannot get around this. In Safari, adding `role="text"` to the container element will force VoiceOver to treat it as a single block of text, but that's a nonstandard role and is ignored by all other browsers.
>
> I only have access to VoiceOver, so I cannot test this behavior with other screen readers, unfortunately, but the internet seems to think it should work as expected with them. VoiceOver is the oddball.
- closes #1016
=> Fix the timestamp in the screen reader narrative for current conditions

web/themes/new_weather_theme/assets/js/components/combo-box.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml, web/themes/new_weather_theme/tests/components/combo-box-tests.js
Previously, in an effort to deal with Safari's non-standard behavior when dealing with focus in shadow doms, I made an attempt to switch from `blur` to `focusout` in order to better capture the click event on a list item before the list hides. The solution that actually worked, however, was to use the [`delegatesFocus`](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/delegatesFocus) property on the shadow dom. I forgot to switch back to `blur`. Only this weekend when trying to use beta from my phone, on which I use FF mobile, did I see that I couldn't select a location.
Not sure how we want to handle this kind of stuff in the future. I suppose we are only using chromium for e2e testing? Should we consider multiple backends if possible?
=> Fixing bug in FF where click evens on list items were not working

web/config/sync/field.field.node.weather_story.body.yml
This PR disables the option to change input formats and restricts content to "basic HTML," allowing only the HTML tags we previously established in #1020.
For reference, those are:
- bold
- italic
- links
- lists (bulleted and numbered)
- block quotes
- heading levels 2 through 6
=> Only allows predefined HTML elements in weather stories

tests/e2e/cypress/e2e/territories.cy.js, web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php, web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/DailyForecast/HourlyData.php.test, web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/HourlyForecast/HourlyForecast.php.test, web/modules/weather_blocks/src/Plugin/Block/Test/HourlyForecastBlock.php.test, web/modules/weather_data/src/Service/DailyForecastTrait.php, web/modules/weather_data/src/Service/HourlyForecastTrait.php
For the current day, change which hours we show:
- show through 6 AM the next day, if the current local time is before midnight
> Eg:
> If it is currently 8pm on a Thursday, the hours will range from 9pm Thursday through 6am Friday. In this case, we are adhering to NWS day rules, and "now" is Thursday.
- show through 6 AM the third day, if the current local time is after midnight
> Eg:
> If it is currently 2am on a Thursday, the hours will range from 3am Thursday through 6am Friday. In this case, we are effectively treating "now" as Thursday, even though by NWS rules it's still Wednesday.
---
- closes #999 
- closes #1000
=> Update hourly table behavior and add appropriate tests

.github/workflows/modules-updated-pr-comment.yaml, composer.json, composer.lock, docs/code-review-templates/code-review-web.md, docs/dev/contributed-modules.md, docs/dev/extend.md
#1028 
Not sure how useful the Github action actually is, and it won't catch dev-only modules. Those aren't the most important, but still nice to have information on.
=> Document our contributed modules

web/modules/weather_routes/src/Controller/LocationAndGridRouteController.php
This is a not-ideal solution to case-insensitive URLs. Technically URLs are case-sensitive according to specification, but we don't have to treat them that way. Drupal doesn't! What Drupal *does* do, however, is use the case-sensitive version of the URL path to determine which Twig file to use and it expects the Twig filename to exactly match the case-sensitive URL path.
This PR works around that by issues an HTTP redirect if the URL path has any uppercase characters.
The primary drawback here is that if a user comes to a URL that has uppercased characters, we force them to make an additional network request before we show them anything. This may be a minor concern – we will never *generate* uppercase URLs, so someone will likely have had to manually type it that way, which seems like it …
=> Redirect URLs with uppercase letters to lowercase instead

tests/e2e/cypress/e2e/location-page.cy.js, web/themes/new_weather_theme/assets/js/components/TabbedNavigator.js, web/themes/new_weather_theme/assets/js/radar.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml
This PR addresses #1038. There are situations where the radar will not load, specifically if the parent container it inserts itself into is not visible on the page at the time it's loaded. 
The solution we've opted for here is to have the `wx-tabbed-nav` dispatch a custom event that has details about which tabId was selected whenever a tab is selected. The event is called `wx:tab-switched` and the event object's `detail` object has a `tabId` key which corresponds to the id of the selected tab.
We use this in the radar library to see if the `current` tab has been switched to -- even on loading. If it has, then we know we can safely try to init the radar component.
Added two e2e cypress tests to make sure the behavior is working
#1038
=> Radar loading fix

web/themes/new_weather_theme/assets/js/radar.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml
This PR addresses #1099. We have tried several times to fix radar loading, but keep coming across inconsistent behavior in our live environments.
There are two key changes in this PR.
First, we are swapping the `async` property on the radar wrapper script tag with `defer`. This allows it to take advantage of the `DOMContentLoaded` event, after which we can attempt to load the radar based on whatever the status is of the actual NWS radar library.
Second, we wrap initialization of the radar component in _both_ the `DOMContentLoaded` event handler _and_, if needed, the tab switch event. This is because sometimes the page loads with the current tab displayed first.
=> Radar fixes: round 2

docs/dev/review-standards.md
We have decided to disable merge queues because they make simple fixes take FOREVER, and they don't really benefit us very often. Instead, we've enabled a requirement that PRs be up-to-date before they can be merged, which gains us the same peace of mind without requiring all of our PRs to be built twice.
Also we haven't used squash merging in a long time.
=> Update docs related to how we merge

web/config/sync/file.settings.yml
Three config files changed in beta:
- `file.settings` - saved here
- `field.storage.node.field_image` - already covered by config split patch
- `system.file` - already covered by config split patch
=> Sync config from beta

web/themes/new_weather_theme/templates/layout/page.html.twig
There's an old, old, old, old, old [Drupal issue](https://www.drupal.org/project/drupal/issues/1503146) where the `is_front` variable doesn't work if your site settings refer to the front page by a URL alias, which is exactly what we do because we don't really want it tied to a particular content ID since that's inconsistent across environments.
This PR changes the check from `is_front` to instead look at the page path. If the page is `/home` (which is our alias to the front page), then it loads the front page layout.
=> Change how we determine when to load the front page layout

.github/actions/build-drupal-image/action.yml, .github/actions/populate-database/action.yml, web/modules/weather_data/src/Service/Test/WeatherAlertParser.php.test, web/modules/weather_data/src/Service/WeatherAlertParser.php
We look for alert overviews as lines that begin and end with ellipses (`...`). Previously, the regular expression we used would match any line that had two sets of ellipses in it. This PR modifies the regex so the ellipses must be at the very beginning and very end of the line.
Fixes #1154 
Fixes #1146
=> Anchor the regex for identifying alert overviews

spatial-data/lib/prep.js
Use the `unzip -t` command to check if a zip file is valid before attempting to unzip it. If it's not, try downloading it again.
- fixes #810
To test it locally, I added a `return` statement after line 46 of `load-shapefile.js` so the script wouldn't attempt to actually load anything into the database, updated the metadata version to `2` in `sources/counties.js`, and then invalidated my counties zip file by running `truncate -s -50k spatial-data/c_05mr24.zip`.
Then I ran the script, saw it identify the corrupted zip, and watched as it downloaded it afresh.
=> Retry downloading corrupted zip files

tests/api/data/testing/points/47.212,-123.107.json, tests/api/serve.js
This PR extends the bundle metadata to include a `status` property. If that property is set, the proxy will return with that HTTP status code.
```json
{
"@bundle": {
"status": 404
}
...
}
```
This approach allows us to test any HTTP status rather than just 503. This PR also adds a new `/points/lat,lon.json` proxy file that results in a 503 status.
closes #917
=> Support HTTP status codes in the API proxy

tests/e2e/cypress/e2e/hourly-forecast-table.cy.js, tests/e2e/cypress/e2e/tabbed-nav.cy.js, web/modules/weather_data/src/Service/AlertTrait.php
The API provides us with a whole OID URN for each alert, which is a bit too long to be useful, but embedded within the URN is a UUID for the alert itself. The rest of the URN is information about what kind of object is being identified (an alert as defined by the World Meteorological Organization and issued by the United States), but we can take those for granted and don't need to include them.
Closes #862
=> Use alert UUID for in-page hash links

web/themes/new_weather_theme/assets/js/components/HourlyTable.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml
This PR implements the changes in #972, which called for the hourly table scroll buttons to scroll more than just one column at a time.
Instead of scrolling one column, each direction will attempt to scroll one full "page" (ie width of the table) view in the relevant direction. It will then attempt to align on the nearest intersecting column on the left, so that the whole column is visible.
=> Hourly table scrolling

tests/e2e/cypress/e2e/hourly-forecast-table.cy.js, tests/e2e/cypress/e2e/tabbed-nav.cy.js, web/modules/weather_data/src/Service/AlertTrait.php
Include more of the OID in the alert ID until we sort out what's going on with CAP.
@loganmcdonald-noaa This should unblock your PR.
=> Fix how we id alerts

web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig, web/themes/new_weather_theme/templates/partials/radar.html.twig
This PR adjusts the headings on the current tab, making the "Current conditions" heading SR only (discussed with @kmranjo) and updating the alignment of "Radar" to left align with the other elements on the page on mobile.
=> Adjust headings on current tab

.github/workflows/modules-updated-pr-comment.yaml, web/config/sync/core.extension.yml, web/modules/weather_cms/weather_cms.info.yml, web/modules/weather_cms/weather_cms.module
Leverages the [hook_field_widget_single_element_form_alter](https://api.drupal.org/api/drupal/core%21modules%21field%21field.api.php/function/hook_field_widget_single_element_form_alter/10) to change our help text on alt text for images, thus fixing #1200 cc/ @kmranjo. 
I have added another module that is super small and only does this thing for our CMS hooks and functionality. 
Note that this will change alt text help text on _any_ image, not just in the weather story. Right now we only have an image in the weather story so it shouldn't be too much of a concern.
=> adds a new module weather_cms and adds a hook for changing alt text on images

web/config/sync/user.role.content_admin.yml, web/config/sync/user.role.content_editor.yml
Adds permissions for `content administrator` and `content editor` roles so they can use the content moderation transitions created in #1242. Without this update, only admins can create content, publish it, or unpublish it. 😬
=> Fix content moderation permissions

web/themes/new_weather_theme/templates/block/block--weathergov-location-search.html.twig
I think we're fine without this – Drupal appears to ignore it since it doesn't show up in the libraries file – but it's dangly cruft, and we might as well clean it up. This can be rebased to main if #1281 gets merged first.
=> Remove old LocationSearch from attached libraries

web/themes/new_weather_theme/templates/partials/alert-link.html.twig
The alert links in the hourly table were having their line heights set higher than default text, resulting in the text rendering slightly lower in the alert box in the hourly table than outside the table. This PR explicitly sets the line height on the alert link so it's consistent everywhere.
- closes #1300
=> Fix alert link styling

web/modules/weather_data/src/Service/AlertTrait.php, web/modules/weather_data/src/Service/SpatialUtility.php, web/modules/weather_data/src/Service/Test/SpatialUtility.php.test
Due to a bad assumption about what the API returns (I assumed it was always polygons or nothing), the process by which we converted an alert geometry into a SQL query would break on multipolygons. This PR implements a new helper method called `geoJSONtoSQL`, which takes the entire GeoJSON object (instead of just the list of points) and uses the GeoJSON geometry type as a switch for what kind of WKT text to create.
- fixes #1331
=> Fix a bug with transforming GeoJSON to WKT

web/themes/new_weather_theme/new_weather_theme.libraries.yml
We failed to update some javascript library versions before the v.1.0.0 release. This means that browsers that were caching the JS files were loading the page incorrectly, due to new element class names etc.
I believe this PR fixes the issue by updating the versions on all relevant / changed js libraries
=> Updating relevant library versions for v1.0.0

Dockerfile.dev, composer.json, composer.lock, web/config/dev/.htaccess, web/config/dev/setTime.php
- Installs [uopz](https://github.com/krakjoe/uopz) for PHP core method overwriting and [clock-mock](https://github.com/slope-it/clock-mock) for time faking
- Adds an Apache conditional so that if there is a `time` query parameter, it loads a `setTime.php` script before handing anything off to Drupal
- Adds the `setTime.php` script which attempts to freeze time based on the `time` query parameter
With this, you can set Drupal's clock by providing a query parameter, like so:
[http://localhost:8080/point/34.749/-92.275?time=2024-06-17T20:00:00-600](http://localhost:8080/point/34.749/-92.275?time=2024-06-17T20:00:00-600)
...which gives you Little Rock, AR, at 9 PM tonight, June 17, 2024.
I think this should work fine alongside what you have. If the setting is empty and the environment …
=> Alternate method for getting times in Drupal

phpunit.xml, web/themes/weathergov_admin/assets/js/weather-story-modal.js, web/themes/weathergov_admin/templates/page--node--add--weather-story.html.twig, web/themes/weathergov_admin/weathergov_admin.libraries.yml, web/themes/weathergov_admin/weathergov_admin.theme
After eons, this PR addresses #1269. The gist is that when creating a new Weather Story and entering a linked WFO, authors should see a dialog of some sort informing them that there is another Weather Story already published with the same WFO. The dialog will have options to save a draft, cancel, or "replace" -- meaning unpublish the other Weather Story first, then publish the new one.
**No.**
I spent a significant amount of time trying to get this "confirmation, with original form data" concept to work via various Drupal APIs and patterns. None of them worked.
After _days_ of poking at it, I threw my hands up and decided to go with Javascript and some basic hook/template alterations.
We add a custom [JS file](https://github.com/weather-gov/weather.gov/blob/eg-1269-basic-js-ws-confirmation …
=> Weather Story WFO Publish Confirmation

web/config/sync/field.field.node.dynamic_safety_information.field_weather_event_type.yml, web/modules/unique_content_field_validation/src/Plugin/Validation/Constraint/UniqueContentTitleValidator.php, web/modules/unique_content_field_validation/unique_content_field_validation.module
Updates the unique content validator to add `%nodeId` as a template variable. In the user-provided validation error message, the `%nodeId` token will be replaced with the ID of the preexisting node for this the uniqueness constraint (in this case, weather event type).
The in config, updates the validation message to encapsulate the node ID into a link to that node's edit form.
- closes #1335
=> Add link to preexisting content on duplicate safety info

web/themes/new_weather_theme/new_weather_theme.libraries.yml
This PR updates the library date for `HourlyTable.js` to reflect the changes that were added as part of #1334. I believe the old date is causing a browser cache issue that results in the bug in #1411
=> Update hourly table library date

docs/architecture/decisions/0016-we-will-use-core-translations-for-interface.md
This PR addresses #1343 by providing an ADR for how we will initially set up internationalization for static / templated text.
This is just the ADR. A follow-on PR will be filed that includes the initial implementation for English.
=> ADR for basic internationalization (1343)

web/themes/new_weather_theme/assets/css/radar/cmi-radar.6602f65c.css, web/themes/new_weather_theme/assets/js/radar.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml
- Updates our libraries to point to the latest deployed version of the CMI library
- Updates our local copy of the CMI CSS to the latest
- Updates how we initialize the CMI component to include two new required settings (set to null since we don't use them, but they are required by schema validation)
- Updates selector used to remove the menu from the DOM
If you pull it down locally, radar should work now.
=> Update to latest CMI library

web/themes/new_weather_theme/templates/partials/alerts-in-hourly-table.html.twig
This PR updates the alert table heading in the hourly table to always display for screen readers. Currently it was only displaying for the first alert row, resulting in empty table headers which is flagged as an a11y error. 
There is no visual change to the table
=> Hourly table alert header a11y fix

.github/ISSUE_TEMPLATE/developer-onboarding.md
- add a note about GitHub account needing to be strictly for government use (that is, if you also use your current GitHub account for personal stuff, you'll need a gov-specific one per NOAA policy)
- adds a step for getting a NOAA account
=> Update onboarding tasks

.github/actions/setup-site/action.yml, web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig
This PR reduces the spacing for the county region lists in the alert details. Currently the spacing for these headings and lists is a little wide, and can be tightened up to create groupings of content and preserve a bit of vertical space.
=> Reduce spacing for alert county lists

.github/actions/setup-playwright/action.yml, playwright.config.js
> It appears that Microsoft’s API for reporting the latest Edge builds is missing build information for Linux systems. Our CI/CD runs in Linux systems, so it’s unable to find a download for Edge, which causes the tool we use for testing to fail. We’re not sure exactly where the issue is, but we’re hopeful it’ll resolve itself in the next couple of days. In the meantime, we’re still poking around to see if we can find any information from Microsoft or the tool we use.
Until a stable version becomes available, disable. We should check in on this in a week.
=> Disable microsoft edge until a working version becomes available

.github/actions/populate-database/action.yml, .github/actions/setup-site/action.yml, spatial-data/lib/prep.js, spatial-data/sources/zones.js, web/modules/weather_data/src/Service/AlertUtility.php, web/modules/weather_data/src/Service/Test/AlertUtilityGeometry.php.test
Previously, we'd encountered a situation where the zones shapefile could include multiple entries for a single zone. We mistakenly believed this was simply a duplication. However, zones are sometimes described by multiple polygons. We only kept the first polygon we encountered for a given zone, resulting in a couple dozen zones that had wildly incorrect geometries. Worse, it meant we could sometimes tell a user that there were no alerts for them because we had a misrepresentation of zones in our database. And it showed up visually (see #1409) where we drew the zone on the map, but what we drew was not the entire zone.
To fix this, our zones table is modified to expect a geometry collection for its `shape` column. When we import zones from the shapefile, we collect all geometries for a …
=> Fixes a bug with how we load forecast and fire zones from shapefile

web/modules/weather_blocks/src/Plugin/Block/AlertInfoBlock.php, web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/Alerts/AlertInfo.php.test, web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/schemas/alertInfo.json, web/modules/weather_data/src/Service/AlertTrait.php, web/modules/weather_data/src/Service/AlertUtility.php, web/modules/weather_data/src/Service/Test/AlertUtility.php.test, web/modules/weather_routes/weather_routes.routing.yml, web/themes/new_weather_theme/templates/block/block--weathergov_info_alert.html.twig, web/themes/new_weather_theme/templates/layout/page--info--alerts.html.twig
This PR changes how we manage metadata about our alerts to be a little more explicit about how they are prioritized against each other, what kind of hazard they are (land, hazard, etc.), and their broader subcategories (we invented this grouping; it's currently `warning`, `watch`, and `other` – we use it for color keying).
While I was in here, I added a page at `/info/alerts` that shows a table of this information. Now we can see all of the alert types we know about, how we prioritize them, what we think they are, etc.
https://weathergov-greg.app.cloud.gov/info/alerts
closes #1407
=> Refactor alert metadata and add an alert metadata page

Dockerfile.dev
Just what it says on the tin. I dunno why we didn't do this sooner. Now in your dev environment, if you make changes to PHP code, you don't need to rebuild the container or clear the Drupal cache in order for the changes to become effective.
=> Disable PHP opcode caching in dev

.github/actions/setup-playwright/action.yml, playwright.config.js
Playwright's built-in tooling fetches browsers for us. I don't know why we added the `setup-browser` step, but getting rid of it and re-enabling MS Edge, tests go back to working.
Spiritual reversion of #1461 
The only way I know to verify what browsers were tested is to download the test report and visually verify that MS Edge is in the report.
=> Rely on Playwright's built-in tools for downloading browsers

docs/dev/spatial-data.md, spatial-data/lib/meta.js, spatial-data/lib/schema.js, spatial-data/load-shapefiles.js, spatial-data/sources/counties.js, spatial-data/sources/countyWarningAreas.js, spatial-data/sources/places.js, spatial-data/sources/states.js, spatial-data/sources/zones.js
This PR modifies how we manage our spatial data schemas and data. The various `spatial-data/sources` file are all updated accordingly.
- source modules export a single object that identifies the involved table, a list of schema upgrades, and a function for loading data
- the keys for the schema upgrades is a schema version
- the values for schema upgrades is a function that makes any necessary schema mutations and returns `true` if source data should also be reloaded or `false` if the schema modification is sufficient on its own
- the `meta` module is updated accordingly
- a new `schema` module is added to handle migrating schemas
- the main `load-shapefile.js` file is modified to be source-agnostic; it can rely on each source plus the schema migration module to handle themselves
Overall, …
=> Update how spatial schemas are managed; update zone schema to add spatial index

web/themes/new_weather_theme/templates/layout/page--point.html.twig
#1495 pulls AFD data from the backend and added it to the point location page in its raw, unformatted state. However, it should not be shown until we've done at least a first pass of formatting.
=> Remove AFD from point page for now

tests/pages.json, web/themes/new_weather_theme/templates/partials/satellite.html.twig
#1310 added satellite imagery to the "current" tab. The satellite imagery should be hidden from assistive technology because it has the `aria-hidden` attribute; however, we should also set the `alt` attribute for technologies to fall back on if they don't support `aria-hidden`. This PR does that.
This PR also puts the "current" tab back into our accessibility testing flow. It fell out by accident when the tab was renamed from "today" to "current."
=> Add empty alt text to satellite image

web/modules/weather_blocks/src/Plugin/Block/Test/EndToEnd/00_EndToEndBase.php.test, web/modules/weather_data/src/Service/AlertTrait.php, web/modules/weather_data/src/Service/AlertUtility.php, web/modules/weather_data/src/Service/Test/AlertUtilityGeometry.php.test, web/modules/weather_data/src/Service/WeatherDataService.php, web/modules/weather_data/weather_data.services.yml
Instead of unioning all zone or county polygons into a single polygon, we now "collect" them into a single geometry collection and then geographically simplify it. Creating a union of the polygons was taking entirely too much time in the case where an alert covers several zones with complex geometries (for example, coastal boundaries).
This PR also caches the collected and simplified polygon based on alert ID. If we already have the computed polygon in cache, we return that immediately rather than rebuild it for every single request.
- closes #1521
=> Simplify how we put together polygons for alerts

web/modules/weather_i18n/translations/en.po, web/themes/new_weather_theme/templates/partials/wind.html.twig
- removes the wind direction arrow if the wind speed is zero
- replaces the "0 mph" with the word "calm" if the wind speed is zero
closes #1518
<details>
<summary>null wind</summary>
</details>
<details>
<summary>zero wind</summary>
</details>
<details>
<summary>some wind</summary>
</details>
=> Update wind speed behavior

web/modules/weather_blocks/src/Plugin/Block/Test/WFOPromoBlock.php.test, web/modules/weather_blocks/src/Plugin/Block/WFOPromoBlock.php, web/modules/weather_data/src/Service/WeatherEntityService.php, web/themes/new_weather_theme/templates/block/block--weathergov-wfo-promo.html.twig
Instead of returning a WFO promo node, the WFO promo block now returns information from a corresponding WFO info node. The WFO promo block template is also updated so that instead of simply being a pass-through to a node template, the promo template now does layout itself.
WFO promo if there is no WFO info node:
WFO promo if there is a WFO info node:
- closes #1471
=> Modify WFO promo block to serve data from the WFO info content type

.github/ISSUE_TEMPLATE/developer-onboarding.md
When we onboard a new teammate, we should add them to the contributors list. We forgot once. That's too much. So let's add this step to our template to make it more likely that we do it properly next time.
=> Update the onboarding template to include adding the new teammate to the contributors list

.eslintrc.js, api-interop-layer/.gitignore, api-interop-layer/data/db.js, api-interop-layer/package-lock.json, api-interop-layer/package.json, api-interop-layer/util/fetch.js, api-interop-layer/util/fetch.test.js, api-interop-layer/util/sleep.js
=> Add API retry-and-backoff + tests

web/modules/weather_data/src/Service/NewRelicMetrics.php
Send timestamps to New Relic properly.
Before: 
```json
[{"metrics":[{"name":"wx.observation","type":"gauge","value":2127.3710043474975,"timestamp":false,"attributes":{"withinGridCell":false,"stationIndex":0,"obsStation":"LBNL1","distance":2127.3710043474975,"usesReferencePoint":true,"applicationName":"local"}}]}]
```
After:
```json
[{"metrics":[{"name":"wx.observation","type":"gauge","value":2127.3710043474975,"timestamp":1725906130,"attributes":{"withinGridCell":false,"stationIndex":0,"obsStation":"LBNL1","distance":2127.3710043474975,"usesReferencePoint":true,"applicationName":"local"}}]}]
```
The Elvis operator is a shorthand for ternary operator and is so called because it looks like Elvis with his signature hairstyle. ([Wikipedia](https://en.wikipedia.org/wiki/Elvis_operator)) …
=> fix NR: use elvis instead of null operator

api-interop-layer/.c8rc.json, api-interop-layer/data/alerts/index.js, api-interop-layer/data/alerts/index.test.js, api-interop-layer/data/alerts/sort.test.js, api-interop-layer/mocha.js, api-interop-layer/package.json
Adds alert sorting testing
- closes #1596
=> [Interop layer] Alert sorting test

api-interop-layer/data/alerts/index.js, api-interop-layer/data/index.js, api-interop-layer/data/points.js, api-interop-layer/data/satellite.js, api-interop-layer/main.js, api-interop-layer/util/fetch.js, api-interop-layer/util/monitoring/index.js
- Adds a super basic logger that just writes to the console, which may be sufficient for cloud.gov. The message format is meant to be machine-parseable even when it's multiple lines, but I don't care much about it, so if it's objectionable, we can change it.
- Removes `console.log` statements elsewhere in the interop layer and replaces them with the new logger calls. Also adds a bunch of verbose logs, just for funsies.
- Sets the default log level to `info` and supports changing it via environment variable.
I imagine #1593 could build on top of this?
=> [Interop layer] First iteration of abstraction for logging and monitoring

.github/workflows/code-standards.yaml, api-interop-layer/data/alerts/index.js, api-interop-layer/data/index.js, api-interop-layer/data/obs/index.js, api-interop-layer/main.js, tests/e2e/cypress/e2e/hourly-forecast-table.cy.js, web/themes/new_weather_theme/assets/js/localizeTimestamps.js, web/themes/new_weather_theme/templates/partials/location-search.html.twig, web/themes/new_weather_theme/templates/point/observations.html.twig
- updates some tests to reflect changes in how data is fetched, specifically the alert end-to-end tests, since they now return more alerts than previously.
- this is because we fetch all active alerts, not just state-based alerts; some of the alerts in our non-Arkansas state-based alert files were, in fact, for Arkansas; merging those together resulted in more alerts. Rather than culling those, I opted to updated the tests
- bug fixes:
- a bug where the observation icon was not being properly parsed, or displayed correctly in the Twig template
- a bug where a timestamp element with an empty `datetime` property resulted in a console error
- a bug where alerts with an unknown event type would crash the interop layer
=> [Interop layer] Test updates

api-interop-layer/data/obs/index.js, api-interop-layer/data/obs/valid.js
The observation handler assumed that if the observations endpoint returned data, it would be a list of one or more `features` each with a `properties` property. However, it is possible to receive a list of zero `features`, and we didn't account for that. Now we do.
Testing of this will get rolled into #1606
=> [Interop layer] Fix a bug in the observations handler

web/themes/new_weather_theme/templates/partials/hourly-table.html.twig
The data returned by the interop layer is nested under unit properties, like this:
```js
{
...
temperature: {
degF: 32,
degC: 0
}
}
```
So when we map in the data for the charts, we need to account for that. No biggie.
=> [Interop layer] Fix charts

web/modules/weather_data/weather_data.module, web/themes/new_weather_theme/templates/layout/page--point.html.twig
In the current site, we catch API request failures and put an error block around them. With the switch to the interop layer, I forgot to add an exception handler. This PR adds a try/catch around the single call to the interop layer and modifies the point page template to show a top-level warning if that failed.
@partly-igor I just slapped some text into the error box. Right now it says
> ~Something went wrong loading this page. Unfortunately we don't have any more information to share right now, but we'll look into it. In the meantime, please try again in a few minutes.~
> Something went wrong loading this page. Please try again in a few minutes.
Happy to change it to whatever.
=> [Interop layer] Add top-level error handling to Drupal

web/themes/new_weather_theme/templates/partials/afd.html.twig
Oops -- the raw text is present on AFD views at the bottom of the page (I use this for debugging, and accidentally committed)
=> [HOTFIX] Raw AFD text

web/modules/weather_data/src/Service/WeatherEntityService.php, web/modules/weather_data/src/Service/WeatherTwigExtension.php, web/modules/weather_data/weather_data.services.yml, web/themes/new_weather_theme/templates/block/block--weathergov-wfo-promo.html.twig, web/themes/new_weather_theme/templates/layout/page--point.html.twig
Fix for #1681 
We "normalize" the WFO code -- meaning we make ALU and AER into AFC -- in two places:
- In the WFOPromoBlock code, so that it attempts to retrieve the information for the Anchorage WFO info page and links to it on a given point location page;
- In a new custom Twig filter, which lets us apply this transformation from within templates as needed
These two links should have both (a) a correct AFD link at the top of the forecast daily page, and (b) The correct link and text at the bottom linking to "Your weather office" (Anchorage/AFC):
- http://localhost:8080/point/55.204/-162.704?#daily
- http://localhost:8080/point/61.217/-149.9?#daily
=> Fix Anchorage WFO Promo links

tests/playwright/e2e/afd-page.spec.js, web/modules/weather_data/src/Service/DataLayer.php, web/modules/weather_routes/src/Controller/AFDController.php, web/modules/weather_routes/weather_routes.routing.yml
Deals with #1729, in addition to more general problems with API response handling.
Before this PR, the `DataLayer`'s `fetch` function was treating API responses of 4xx and 5xx both as generic `500` errors. Those generic errors are difficult to properly "catch" and reason about in the Drupal routing system.
We have changed this so that we make the appropriate distinction. Additionally, the result of `fetch` is more comprehensive (an array of information, including whether or not the result was an error-level response).
Finally, we have wrapped some of the more API-request-heavy parts of the AFD controller in try blocks. All exceptions caught from API requests here will trigger a `NotFoundHttpException()`, which will lead to the generic 404 page.
In addition to the source ticket, we also …
=> AFD 404s (and other things!)

Makefile
This PR removes the `fix-permission` recipe from the Makefile because running that command is creating a large set of changed files with git.  Suggested by @eric-gade 
We may need to adjust file permissions manually without this in place.
=> Remove fix permissions recipe

web/themes/new_weather_theme/assets/js/components/alertMap.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml
The Leaflet, ESRI and ESRI vector script tag `id` attributes were mistakenly removed, so the alert map module could never determine when those scripts had loaded. Additionally, Drupal controls the rendering order of our script tags so we cannot be certain that the DOM will be fully loaded when we load, so if Leaflet isn't already available, also attach a `DOMContentLoaded` event handler.
Alternatively, we could keep calling the Leaflet check on a timer, but in the even that Leaflet never loads, we'd just be burning CPU cycles on nothing. Using event-based loading is more processor-friendly.
=> Fix script bundling

web/themes/new_weather_theme/assets/js/charts/hourly-humidity.js, web/themes/new_weather_theme/assets/js/charts/hourly-pops.js
When we were building the temperature chart, we originally implemented logic to only show the even-numbered hours on the X axis. However, we bumped into a lot of weird behavior with that, so we opted to just let Chart.js figure it out. That seemed to work pretty well.
However, for the hourly precipitation chances and humidity charts, we left in that "only evens" logic. This PR removes that logic so that these two charts also behave like the temperature chart.
- closes #1766
=> Remove custom logic for determining which X axis ticks to display

api-interop-layer/data/forecast/daily.js, api-interop-layer/data/forecast/daily.test.js
Fixes a bug with how overnight periods were determined. The original logic was faulty because it assumed that if the first period of a day was not `isDaytime`, then the period must be overnight. However, that is only half the condition, because an overnight period only happens if there are also day and night periods in the same forecast day. It is totally valid for there to be only a single period in the forecast day, and our previous logic would call that an overnight period even though it cannot be.
This PR updates the logic to update the first period of the first forecast day to be overnight **IF AND ONLY IF** there are three periods in the first day. It also modifies the tests so that the times in the test are expressed in the local timezone so they are easier to reason about …
=> [Interop layer] Fix overnight periods

playwright.config.js, tests/api/data/testing/gridpoints/LZK/83,73.json, web/themes/new_weather_theme/assets/js/charts/WeatherChart.js, web/themes/new_weather_theme/assets/js/charts/hourly-dewpoint.js, web/themes/new_weather_theme/assets/js/charts/hourly-humidity.js, web/themes/new_weather_theme/assets/js/charts/hourly-pops.js, web/themes/new_weather_theme/assets/js/charts/hourly-temperature.js, web/themes/new_weather_theme/assets/js/charts/hourly-wind.js, web/themes/new_weather_theme/assets/js/charts/qpf.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml, web/themes/new_weather_theme/templates/partials/daily-forecast-list-item.html.twig, web/themes/new_weather_theme/templates/partials/hourly-charts.html.twig, web/themes/new_weather_theme/templates/partials/hourly-table.html.twig, web/themes/new_weather_theme/templates/partials/scroll-buttons.html.twig
Adds scrolling arrow buttons to the hourly forecast charts in the 7-day.
In this implementation, the scrolling is synced for all charts via the `data-sync-scrolling` attribute on chart containers.
* Moved scroll buttons into their own template partial
* Moved chart area into its own template partial, and out of the hourly-table element
* Small cleanup
=> Implementing (synced) scroll buttons for charts

Makefile, spatial-data/.gitignore
This PR extends our `zap` utility to first dump the geospatial tables to a SQL file before destroying the database container. Then, after the database container is ready, it imports the geospatial tables from SQL. Finally, it runs the `load-spatial` command which will run any necessary updates. This should speed up our zaps quite a lot since spatial updates are so infrequent.
=> Preserve spatial data when doing a zap

web/themes/new_weather_theme/assets/js/charts/hourly-dewpoint.js, web/themes/new_weather_theme/assets/js/charts/hourly-humidity.js, web/themes/new_weather_theme/assets/js/charts/hourly-pops.js, web/themes/new_weather_theme/assets/js/charts/hourly-temperature.js, web/themes/new_weather_theme/assets/js/charts/hourly-wind.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml
This PR adds the `mouseout` event to the list of tooltip interaction events so that the tooltip is hidden once the user stops hovering over a chart. 
Look no tooltip
=> Add mouseout event for charts to remove tooltip after hover

.github/workflows/deploy-sandbox.yaml, .github/workflows/deploy-staging.yaml, manifests/manifest-design.yaml, manifests/manifest-eric.yaml, manifests/manifest-greg.yaml, manifests/manifest-staging.yaml
Sets up deploy for all environments except beta. Addresses https://github.com/weather-gov/weather.gov/issues/1731
It is not possible to have a rolling strategy for multiple apps defined in a manifest (see cloud.gov [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#deployment-process)). So here we are doing an app deploy one by one. Right now a "rolling" strategy doesn't matter that much because we only have one instance at any given time but it will matter when we add more instances down the line.
=> API interop layer deploy actions

api-interop-layer/data/alerts/geometry.test.js, api-interop-layer/data/alerts/index.js, api-interop-layer/data/alerts/index.test.js, api-interop-layer/data/db.js, api-interop-layer/data/obs/index.js, api-interop-layer/data/obs/index.test.js, api-interop-layer/data/points.js, api-interop-layer/mocha.js, web/themes/new_weather_theme/templates/partials/daily-summary-list-item.html.twig
The MariaDB library that we're using (because there's not a first-party MySQL library, surprisingly) exposes alias methods on the pool object where it automatically fetches an available connection, executes the query, then releases the connection back to the pool. This way the various parts of the app the query the database don't also need to worry about freeing up the connection. At least one module was *not* releasing its connection, which is possibly why running browser tests more than 5-6 times in a few minutes would result in database crashes.
Anyway... this should handle that.
closes #1756
=> [Interop layer] Use a database connection pool

web/config/cloudgov/config_split.patch.field.storage.node.field_fullimage.yml, web/config/cloudgov/config_split.patch.field.storage.node.field_smallimage.yml, web/config/cloudgov/config_split.patch.field.storage.node.field_wfo_sitrep.yml
Enables `s3fs` for newer upload content types on cloud.gov. The config is copied from the pre-existing `config_split.patch.field.storage.node.field_image.yml` and _should_ be all we need here.
To test, `docker compose exec drupal drush config-split:activate cloudgov` (don't forget to deactivate afterwards!)
We will need to test uploads again on staging to make sure uploaded s3 files are persisted. Uploading the newer uploads to s3 is untested.
=> config split: enable s3fs for uploads on cloud.gov

web/themes/new_weather_theme/templates/partials/daily-summary-list-item.html.twig, web/themes/new_weather_theme/templates/partials/today-summary-forecast.html.twig
The today tab forecast summary uses the same component as the daily forecast tab. This component automatically applies an ID to the container based on the forecast date. As a result, we end up with two nodes with the same node ID - one on the "today" tab and one on the "forecast" tab, which causes the quick forecast link to try to go to the wrong place.
This PR modifies the component so that it can accept a node ID as an argument and it will use the date if an ID is not provided, and modifies the today tab to provide an ID. This clears up the ID collision and fixes the link.
=> Set a manual node ID on the "today" tab forecast summary

web/themes/new_weather_theme/templates/partials/quick-forecast-link-item.html.twig
Just a variable name change that we didn't catch elsewhere.
=> Fix alert icon color

api-interop-layer/package.json, docker-compose.yml, docs/dev/debugging.md
This PR turns on the Node.js inspector within nodemon and forwards the inspector ports back to the host machine. Documentation is also updated.
It took several tries starting and restarting the VS Code debugger for it to attach properly, but then suddenly, it did. It's been reliable ever since.
=> Enable debugging for the interop layer in local dev

.bp-config/php/php.ini.d/upload_max_filesize.ini, Dockerfile.dev, web/config/sync/field.field.node.wfo_pdf_upload.field_wfo_sitrep.yml, web/config/sync/field.field.node.wfo_weather_story_upload.field_fullimage.yml, web/config/sync/field.field.node.wfo_weather_story_upload.field_smallimage.yml
As per one of my weather story proposals, bump up the upload limit to 3M. 
Before:
```
error: could not upload file: [{'title': 'Unprocessable Content', 'status': '422', 'detail': 'Unprocessable Entity: file validation failed.\nThe file is 2.76 MB exceeding the maximum file size of 2 MB.', 'links': {'via': {'href': 'http://localhost:8080/jsonapi/node/wfo_weather_story_upload/field_smallimage'}}}]
```
after:
```
error: could not upload file: [{'title': 'Unprocessable Content', 'status': '422', 'detail': 'Unprocessable Entity: file validation failed.\nThe file is 3.29 MB exceeding the maximum file size of 3 MB.', 'links': {'via': {'href': 'http://localhost:8080/jsonapi/node/wfo_weather_story_upload/field_smallimage'}}}]
```
Nada
=> increase dss builder upload limits to 3mb

web/modules/weather_data/weather_data.module, web/modules/weather_routes/src/Controller/LocationAndGridRouteController.php, web/modules/weather_routes/weather_routes.routing.yml, web/themes/new_weather_theme/new_weather_theme.theme
Currently when you browse to a place page, such as https://beta.weather.gov/place/ca/oxnard, we find an appropriate lat/lon and redirect you to a point page: https://beta.weather.gov/point/34.1975/-119.17705
This is not ideal either for SEO or usability. This PR modifies that behavior.
1. If the place name has a space in it, we redirect to the same URL but with the space replaced with an underscore
2. If the state or place name are not capitalized the same as our database, we redirect to the same URL but with the capitalization normalized
3. If the state and place name match our database, we simply render the page instead of redirecting.
The result is that we should end up with mostly canonical URLs for all the places we know about. For example:
```
https://beta.weather.gov/places/ca/los …
```
=> When browsing to a place URL, don't redirect to a point URL

web/config/sync/jsonapi_extras.jsonapi_resource_config.node--wfo_weather_story_upload.yml
We encountered a problem in the staging environment, where the newest updates from `main` were crashing the site.
The issue appears to be the config failing to import properly. Logging into the instance, we found that running `drush config:import` gave the following error output:
<details>
<summary>Click to see the shell output</summary>
```shell
WARN[0000] The "NEWRELIC_LICENSE" variable is not set. Defaulting to a blank string. 
+------------+----------------------------------------------------------------+-----------+
| Collection | Config                                                         | Operation |
+------------+----------------------------------------------------------------+-----------+
|            | field.storage.node.field_derived_wfo                           | Create …
```
=> [HOTFIX] Mismatch in exported config for new derived field

.gitignore, Makefile, README.md, web/config/sync/language.content_settings.block_content.basic.yml, web/config/sync/language.content_settings.block_content.no_title_block.yml, web/config/sync/language.content_settings.content_moderation_state.content_moderation_state.yml, web/config/sync/language.content_settings.file.file.yml, web/config/sync/language.content_settings.menu_link_content.menu_link_content.yml, web/config/sync/language.content_settings.node.dynamic_safety_information.yml, web/config/sync/language.content_settings.node.page.yml, web/config/sync/language.content_settings.node.testing_page.yml, web/config/sync/language.content_settings.path_alias.path_alias.yml, web/config/sync/language.content_settings.taxonomy_term.weather_event_types.yml, web/config/sync/language.content_settings.taxonomy_term.weather_forecast_offices.yml, web/config/sync/language.content_settings.user.user.yml, web/config/sync/language.entity.zh-hans.yml, web/config/sync/language.negotiation.yml, web/modules/weather_i18n/translations/zh-hans.po, web/themes/new_weather_theme/templates/layout/page.html.twig
1. ~Switch from English strings to translation keys as `msgid`s in PO files and Twig templates.~ This will be done on #1579 to have more time to test
2. Add a few static Chinese translations
Todo:
Closes #1540
Translations are accessible at `http://localhost:8080/<lang code>/` for example http://localhost:8080/zh-hans/point/34.749/-92.275 . You'll see a mix of translated text and English text.
Updates to the `.po` files can be imported with `make update-translations`
🚩   http://localhost:8080/zh-hans/ currently results in 404
=> Static Chinese translations

api-interop-layer/data/alerts/backgroundUpdateTask.js, api-interop-layer/data/alerts/backgroundUpdateTask.test.js
Just what it says on the tin, plus tests.
- closes #1841
=> For unknown alerts with "evacuation" in the title, make them equivalent to the NWS-defined "Evacuation Immediate" event

tests/playwright/outside/api.spec.js, web/config/sync/field.field.node.wfo_weather_story_upload.field_fullimage.yml, web/config/sync/field.field.node.wfo_weather_story_upload.field_smallimage.yml, web/modules/weather_cms/weather_cms.module
**NB** https://github.com/weather-gov/weather.gov/pull/2082 should be reviewed/merged first
Partially addresses https://github.com/weather-gov/weather.gov/issues/2033 -- specifically, by overwriting weather story images as they come in. I've also changed it so that uploads use the derived wfo for clarity. 
I've added a logging message for this specific path. Example:
```
drupal-1             | [NOTICE] [weather_cms] [2024-11-18T22:06:32] weather story upload: moving public://National Weather Service/wfo_weather_story_upload/field_fullimage/fullimage1_43.png to public://National Weather Service/wfo_weather_story_upload/field_fullimage/fullimage1.png | uid: 2 | request-uri: http://localhost:8080/jsonapi/node/wfo_weather_story_upload
drupal-1             | [NOTICE] [weather_cms] …
```
=> weather story uploads: overwrite upload

Makefile, api-interop-layer/ecosystem.config.cjs, api-interop-layer/main.js, api-interop-layer/package-lock.json, api-interop-layer/package.json, tests/api/package-lock.json, tests/api/package.json
With PM2, we can now gracefully restart when the API interop layer goes down, and so we exit (error code 1) every time we get an uncaught exception. Closes https://github.com/weather-gov/weather.gov/issues/2001
Does not fix our memory issues but might give us more insight on what's happening under the hood.
- Added a new Makefile target: `im`, so we can peer inside the pm2 and see the metrics/logs. (This is for dev purposes only)
- We are not using `nodemon` anymore for dev, but are using PM2 for both dev/prod, which makes our environments more consistent.
=> Setup PM2 for interop layer

api-interop-layer/ecosystem.config.cjs
PM2 was crashing because it was watching its own pid file. Configure it to watch only javascript files instead.
=> pm2 configuration tweaks

tests/playwright/e2e/afd-page.spec.js, tests/playwright/e2e/alerts.spec.js, tests/playwright/e2e/combo-box-location.spec.js, tests/playwright/e2e/daily-forecast-alerts.spec.js, tests/playwright/e2e/daily-forecast.spec.js, tests/playwright/e2e/dates-are-localized.spec.js, tests/playwright/e2e/hourly-forecast.spec.js, tests/playwright/e2e/invalid-icons.spec.js, tests/playwright/e2e/invalid-locations-are-not-found.spec.js, tests/playwright/e2e/location-page.spec.js, tests/playwright/e2e/location-pages-preserve-browser-history.spec.js, tests/playwright/e2e/qpf-table.spec.js, tests/playwright/e2e/quick-forecast.spec.js, tests/playwright/e2e/quick-toggle.spec.js, tests/playwright/e2e/radar.spec.js, tests/playwright/e2e/tabbed-nav.spec.js, tests/playwright/e2e/territories.spec.js, tests/playwright/e2e/touchpoints.spec.js, web/themes/new_weather_theme/assets/js/point.page.components.js, web/themes/new_weather_theme/assets/js/point.page.js, web/themes/new_weather_theme/new_weather_theme.libraries.yml, web/themes/new_weather_theme/templates/layout/afd-page.html.twig, web/themes/new_weather_theme/templates/layout/page--point.html.twig, web/themes/new_weather_theme/templates/layout/page-metadata-alerts.html.twig
This PR addresses the ongoing ticket #1675, and appears to ameliorate _some_ of our browser test flakiness.
Here's the rub: currently, any custom element components are all bundled up with the functional (non-custom element) components on the point page. These are loaded into a single script tag in the body that is given the "defer" attribute. For custom elements, this means that the functionality of the components might not be fully loaded at page "load" time. That means we are testing for functionality that in a lot of cases hasn't loaded yet (and so the tests fail). It's a matter of timing.
To get around this, we have separated actual custom elements into a separate library bundle for the point page called `point.page.components.js`. This is now loaded without the "defer" attribute, …
=> Browser test tweaks

.eslintrc.js, api-interop-layer/data/alerts/backgroundUpdateTask.js, api-interop-layer/data/alerts/backgroundUpdateTask.test.js, api-interop-layer/data/alerts/cache.js, api-interop-layer/data/alerts/cache.test.js, api-interop-layer/data/alerts/geometry.js, api-interop-layer/data/alerts/index.js, api-interop-layer/data/alerts/index.test.js, api-interop-layer/data/alerts/utils.js
This PR attempts to partially address interop layer refactoring. It implements the alert cache table strategy outlined in the [interop alert refactoring doc](https://docs.google.com/document/d/1xhjscbNdmVywgZgvMksBKP-cJEpfomSMHAIvS7Zyw30/edit?usp=sharing).
Alerts are now cached -- with their geometries, if present -- in a new spatial table called `weathergov_geo_alerts_cache`. This table will be dropped and recreated whenever the interop process (re)starts. It's schema is defined in code (see inline comments).
The interface into the alerts cache table is a helper object called `AlertsCache`. Instances of this object contain immutable functions for interacting with the cache table. The advantage is that you can make several instances of this object and they will not interfere with each …
=> Alerts cache table

.gitlab-ci.yml, docker-compose.yml
Docker-in-docker example for building our own images and pushing to the Gitlab repository. [Example run](https://vlab.noaa.gov/gitlab-licensed/NWS/Systems/DIS/Weather.gov-2.0/-/jobs/2787).
Note that we can attach rules, e.g. build when these files have changed:
```yaml
rules:
- changes:
compare_to: 'refs/heads/main'
paths:
- Dockerfile.utility-node
- ./package-lock.json
- ./api-interop-layer/package-lock.json
- ./tests/api/package-lock.json
```
But for now I've made this an optional manual step until we have some form of versioning in place. 
- I added a project name to our `docker-compose.yml` -- this is needed, otherwise the default project name will be derived from the directory and hence will be `weathergov-20` in our CI setup.
- This docker-in-docker setup was given to us by the vlab …
=> gitlab ci: build and push utility image

web/modules/weather_data/src/Service/WeatherEntityService.php
We discovered today that WFO ids are canonically four characters.
> Not all of them start with a "K," e.g. Guam (PGUM). I can't imagine any conflict ever in reality, but the full, proper call signs are four characters.
This fixes for DSS builder weather story image matching by throwing away the first character.
=> dss builder: bugfix to accommodate 4 char WFO ids

.gitlab-ci.yml, Makefile, docker-compose.yml, docs/dev/gitlab-ci.md
Does what it says on the tin: generalize build (does not work for `database` yet) and documents Gitlab CI as it is right now ([rendered](https://github.com/weather-gov/weather.gov/blob/fd5bf0118f2688fcc532768d481f59f0f1a6df8b/docs/dev/gitlab-ci.md)). 
- There is no good way to name an image -- it is derived from the docker compose yaml. So I add a derived variable but we might be able to clean this up later.
- A dot before the gitlab pipeline means "do not execute directly" -- here, we use `.build-image` as a template to be extended.
=> gitlab ci: generalize build and add documentation

manifests/manifest-beta.yaml
We are currently using ~4gb out of our memory quota. Let's go ahead and give the api interop some extra memory. 
we got another instance of the api interop layer crash-loop of doom :tm: so this is (likely) a short term solution
=> bump up api interop to 1024M

web/modules/weather_data/src/Service/WeatherEntityService.php
Quick fix-- don't truncate the WFO but rather query the WFO ending. e.g., searching for WFO with `IWX` will match these with `SIWX`.
=> fix WFO canonical mapping

web/modules/weather_i18n/translations/en.po, web/themes/new_weather_theme/templates/block/block--weathergov-weather-story-image.html.twig
To help reduce confusion until we can implement some fixes to old weather stories showing with incorrect dates:
* hide the timestamp
* add the "under development" icon
Without a weather story:
=> Hide timestamps and add construction icon

web/modules/weather_data/src/Service/WeatherEntityService.php
This PR tries to limit stories selected for display to those where the current server time is within the UTC start/end times given by the weather story XML.
James, I faked some timestamps to test this on local, but I would love if we could copy a bunch of actual stories from beta. Do you already have a script that can do that?
=> Fix expired weather stories

web/config/sync/core.entity_form_display.taxonomy_term.weather_forecast_offices.default.yml, web/config/sync/core.entity_view_display.taxonomy_term.weather_forecast_offices.default.yml, web/config/sync/field.field.taxonomy_term.weather_forecast_offices.field_weather_story_opt_out.yml, web/config/sync/field.storage.taxonomy_term.field_weather_story_opt_out.yml, web/modules/weather_blocks/src/Plugin/Block/Test/WeatherStoryImageBlock.php.test, web/modules/weather_blocks/src/Plugin/Block/WeatherStoryImageBlock.php, web/modules/weather_data/src/Service/WeatherEntityService.php
We want to be able to give admins in the CMS the ability to opt certain WFOs out of having weather stories show up. This PR adds a bool field to the weather field office taxonomy, sets the default to true, and allows admins to check a box if they want to opt an office out.
Before merging, I'll test in staging where we have some stories and create documentation for our admins.
=> add opt out for weather stories
