docs/architecture/decisions/0001-record-architecture-decisions.md

Date: 2023-05-24
Proposed
We need to record the architectural decisions made on this project.
To record significant decisions in this project, we will use Architecture
Decision Records as [described by Michael Nygard in this
article](http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions).
See Michael Nygard's article, linked above.

ADR: 0001 - Record architecture decisions

---

docs/architecture/decisions/0002-use-uswds.md
docs/architecture/decisions/0005-use-uswds.md

Date: 2023-07-18
Accepted
Using a design system can eliminate a ton of work for creating a new product. If that design system is also built for accessibility and includes additional features to make accessible design easier, that is an even bigger win.
Design systems help create a consistent user experience by establishing a color palette, defining reusable components, and providing UX patterns for common tasks.
Furthermore, the [21st Century Integrated Digital Experience Act](https://www.congress.gov/bill/115th-congress/house-bill/5759/text) requires that all federal websites comply with the [standards defined by the US Web Design System](https://designsystem.digital.gov/website-standards/).
We have chosen to use the US Web Design System (USWDS). USWDS satisfies the legal requirement of …

ADR 0002 - We will use the US Web Design System

---

.gitignore
docker-compose.yml
drupal-volume/default-site/settings.php

This PR copies the `settings.php` from a newly-installed and configured Drupal install and updates it to use environment variables for database connection information. It then makes that file available via a Docker volume share. The Docker compose script is updated to inject database connection information via environment variables.
Using these changes, restarting the Drupal container does not require re-running the initial install/configure script. Yay!

Updates Docker config to support persistent Drupal configuration

---

docs/architecture/resources.md

This PR adds light documentation around the infrastructure resources we've created in the WOC. This should not be the final form of this documentation, but it serves our immediate needs – not forgetting what we've done. 😄

Document the cloud resources we've created

---

.gitignore
docker-compose.yml
drupal-volume/default-site/default.settings.php
drupal-volume/modules/content_api/content_api.info.yml
drupal-volume/modules/content_api/content_api.routing.yml
drupal-volume/modules/content_api/src/controllers/ContentAPI.php

Adds a super basic module that adds a REST API endpoint. This endpoint just returns the current time and a list of items in a taxonomy with machine name `test`. If you don't have that taxonomy, it'll return an empty array. It's all serialized as JSON.
This PR doesn't need to be merged, necessarily. It's mostly just storing this bit of prototyping somewhere other than my machine, and giving us something we can point at and talk about.

A module to expose a REST API endpoint

---

README.md
composer.json
composer.lock

📢 New Drupal core update available. Core should be updated as soon as a new version is available, since it usually involves security updates.
Updates to 10.1.2

Cannandev/update drupal core version 10.1.2

---

.github/workflows/code-review-templates/code-review-docs.md
.github/workflows/code-review-templates/code-review-full.md

This pull request adds initial files for a PR review checklist inside our workflows. 
The action will be added in a subsequent PR.

add initial CR review checklists

---

.github/workflows/code-standards.yaml
.stylelintrc.js
package-lock.json
package.json
web/themes/new_weather_theme/assets/sass/_uswds-theme.scss

We don't lint our Sass, but we should
Adds stylelint to our CI/CD.

Add SCSS linting

---

.github/workflows/code-standards.yaml

We have committed to 90% test coverage, but we're not currently capturing or reporting it.
This PR updates the PHP unit test step to capture code coverage, and then adds two additional steps to report coverage and enforce a minimum percentage.
Currently our coverage is at 0%, so we'll soon need to dedicate some time to tests while the amount of code we have is still low.

Report code coverage

---

docs/standards.md

We haven't documented those things.
Documents those things. tktk
Closes #128.

Document our code proposal, review, and deployment process

---

docs/architecture/decisions/0007-we-will-use-utility-first-approach-to-css.md

The automation for creating ADRs seems to strip out code blocks. OH NO!
It doesn't. But it fixes one of the ADRs that got bitten. As far as I can tell, this is the only one that's been affected.

Fix ADR 0007

---

.github/workflows/adr-accepted.yaml

Instead of trying to deal with text strings in bash, which handles different kind of quotation marks in wildly different ways and good luck trying to account for them all with arbitrary text input, handle them with Javascript and use GitHub's `toJSON()` expression to stringify the arbitrary input.
Closes #304
Frankly, this is probably easier to reason about and maintain anyway. 🤷‍♂️ 
See #342 and #345 to see how it turned out in practice.

Fix ADR automation

---

tests/a11y/cypress.config.js
web/themes/new_weather_theme/templates/block/block--system-branding-block.html.twig
web/themes/new_weather_theme/templates/layout/page.html.twig

Adds a big ol' beta banner.
This PR isn't tied to a ticket. It just seemed like a good idea (and was an excuse to fiddle with some other Drupal stuff).
- @shadkeene (and Kari, but I couldn't find her in GitHub): Is this something we should have?
- @kmranjo: I just made up some text and plopped it at the top of the page. Now there's a placeholder for someone who knows what they're doing to tell me what the text should be and where it should go!

Add a beta alert banner

---

web/config/block.block.new_weather_theme_userlogin.yml
web/config/core.menu.static_menu_link_overrides.yml

This updates the login block in the structure so that it only displays on the `/user/login` page.
Closes #321
This one is simple!

Move the login block off the front page

---

.github/workflows/code-standards.yaml

Updates our automated tests to pass quickly if only documentation has been changed.
Closes #357
Whew. What a hassle.

Skip tests when only documentation changes have been made

---

bootstrap.sh
manifest.yml
scripts/deploy-cloudgov.sh

some changes to deploy beta site

---

.github/workflows/deploy-sandbox.yaml
manifests/manifest-eric.yaml
manifests/manifest-greg.yaml

Adds environments for Eric and Greg to test features in. 
https://weathergov-greg.app.cloud.gov/
https://weathergov-eric.app.cloud.gov/
Deploy like so: https://github.com/weather-gov/weather.gov/actions/workflows/deploy-sandbox.yaml

remove test, add eric and greg environments

---

web/config/block.block.new_weather_theme_currentconditionsblock.yml
web/config/block.block.new_weather_theme_locationsearchblock.yml

Updates the location search block configuration so that it's available everywhere. And that's pretty much it.
cc: @shadkeene @colinmurphy01

Make location search available everywhere

---

web/themes/new_weather_theme/assets/js/components/locationSearch.js

We use the event bubble to capture input/change events on the location input field.
This is in direct reference to #425 
- Spin up the branch locally
- Open the browser console
- Enter a zip or location into the location search input and expect results
- Check the console for errors
- Refresh the page, repeat several times

Updating to use event bubble / document event handlers

---

Dockerfile.dev
docker-compose.yml
docs/dev/debugging.md
docs/dev/index.md

@eric-gade mentioned getting debugging setup, which yeah, please. Since today's a short day, it made more sense to spend on this sort of thing than starting a whole new big body of work.
A simple `make rebuild` should do the job here, no need to zap or anything. Once you setup your IDE and start it listening, it should... just work? PHP's quirky about where you can put breakpoints, though; for example, you can't break on a `return` statement, it seems? I lost probably 30 minutes trying to figure out why xdebug wasn't connecting, and it was but it was just rejecting that breakpoint. Maybe an optimization thing, I dunno.

Setup debugging

---

web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php
web/modules/weather_blocks/src/Plugin/Block/HourlyForecastBlock.php.test

Change hourly forecast from 4 hours to 12

---

web/modules/weather_data/src/Service/WeatherDataService.php

There is a known bug in the weather.gov API where forecasts in particular sometimes fail with a server error. The current mitigation is to try again. This PR implements and back-off-and-retry approach. If we get a server error, we wait briefly and then attempt it again.
|attempt|delay|
|---|---|
|1|none|
|2|75 milliseconds after the first failure|
|3|124 milliseconds after the second failure|
|4|204 milliseconds after the third failure|
|5|337 milliseconds after the fourth failure|
These errors are logged to Drupal. I'm not sure if they should be since we're mitigating a known bug outside of our control with a planned fix in the backlog, but I did it anyway. Happy to remove it if it feels like a weird sudden addition.
I'll add tests after #499 is merged rather than deal with merge issues …

Retry API calls when they fail due to a server error

---

web/themes/new_weather_theme/templates/layout/footer.html.twig
web/themes/new_weather_theme/templates/layout/page--local.html.twig
web/themes/new_weather_theme/templates/layout/page--user.html.twig
web/themes/new_weather_theme/templates/layout/page.html.twig

- moves the footer into its own template, and updates other templates to `{% include() %}` it
- adds a margin to the top of the footer
- fixes #527
Only needs a make cc

Add top margin to footer

---

web/modules/weather_data/src/Service/Test/UnitConversionTrait.php.test
web/modules/weather_data/src/Service/UnitConversionTrait.php
web/modules/weather_data/src/Service/WeatherDataService.php

Adds a trait for unit conversions so classes that need to do it can just... do it.
Closes #206

Centralize unit conversions

---

web/themes/new_weather_theme/assets/js/components/locationSearch.js

Fixes the logic by which locationSearch activates on a `select` element on the page.
The syntax was wrong. Don't jump between different languages too hastily.

Fixing locationsearch conditional logic

---

docs/environments.md
docs/syncing-content-between-environments.md

Documents the process of importing and exporting content.

Add documentation about how to export and import content

---

.github/workflows/adr-accepted.yaml
.github/workflows/adr-proposed.yaml
.github/workflows/code-standards.yaml
.github/workflows/deploy-beta.yaml
.github/workflows/deploy-sandbox.yaml
.github/workflows/deploy-staging.yaml

Bumps a bunch of the actions we depend on to newer versions to get rid of the deprecation warnings in our action logs.
The action log should be clean now: https://github.com/weather-gov/weather.gov/actions/runs/7670902015
(compare to previous: https://github.com/weather-gov/weather.gov/actions/runs/7660094740)

Update our GitHub action versions

---

.github/workflows/code-standards.yaml
docs/architecture/decisions/0014-we-will-store-and-use-our-own-geospatial-data.md

The ADR automation doesn't work anymore it can't sign its commits. I tried to rebase and sign its commits in #732 but that just screwed everything up. Anyway, take two.

 Add ADR 0014 to the repo

---

.github/workflows/deploy-beta.yaml
.github/workflows/deploy-sandbox.yaml
.github/workflows/deploy-staging.yaml
.github/workflows/new-relic-deployment.yaml
docs/architecture/decisions/0015-we-will-use-newrelic-for-performance-metrics.md
docs/dev/secrets.md
manifests/manifest-beta.yaml
manifests/manifest-eric.yaml
manifests/manifest-greg.yaml
manifests/manifest-staging.yaml
scripts/create-cloudgov-env.sh
web/sites/default/settings.cloudgov.php

This will help add deployment lines to new relic. 
I've also added an ADR with information about new relic as well as fixed our problem with the license env var showing up in github actions logs. 
I've updated all secrets and environments so this should be safe to deploy.

Add New Relic ADR, deployment github action for tracking deployments, and change how we are setting our license

---

spatial-data/load-shapefiles.js

Fixes a text-case bug that showed up in our environments, whose DBs are case-sensitive even though our local versions aren't.

Fixing case-sensitive term for sql

---

tests/e2e/cypress/e2e/tabbed-nav.cy.js
web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
web/themes/new_weather_theme/templates/block/block--weathergov-location-search.html.twig
web/themes/new_weather_theme/templates/layout/page--local.html.twig

* move current conditions into a tab
* give the search box a z-top styling so it's accessible above the tabs
* give the tabs a z-500 styling so they don't obscure the tabs
Closes #790
This was super easy. Whoever put this tab controller in here did a nice job.

Move current conditions into a tab

---

spatial-data/load-shapefiles.js

Updates our places table to get timezone information from the geonames data instead of the counties. The reason is simple: a county can exist in multiple timezones, in which case our county data is funky. The geonames dataset has timezones for all the US places, so let's just use that. Then we also happily get the appropriate timezones for places that don't use DST, too.
Once merged, we'll need to re-load spatial data in all of our cloud environments for this to take effect. In the meantime, places without timezones (a bunch of places in Arizona, some in the Dakotas, etc.) will fail to load hourly forecasts, but everything else will continue to work correctly. This can be done in conjunction with #800.

Get place timezone from geonames instead of counties

---

tests/e2e/cypress/e2e/tabbed-nav.cy.js
web/themes/new_weather_theme/templates/layout/page--local.html.twig

Combine outlook and hourly into today tab

---

docs/dev/git-signing.md

This PR adds a small addition to the git signing section of our docs covering how to add the public key to GitHub

Add section on adding ssh key to GitHub 

---

composer.lock
package-lock.json
package.json
tests/api/package-lock.json

I deployed to my environment and it worked fine. I've since repurposed by environment, but we can always do it again to verify.

Update NPM and composer dependencies

---

.github/workflows/deploy-sandbox.yaml
.github/workflows/new-relic-deployment.yaml
manifests/manifest-beta.yaml
manifests/manifest-design.yaml
manifests/manifest-greg.yaml
manifests/manifest-staging.yaml
manifests/manifest.template.yaml
scripts/create-cloudgov-env.sh
scripts/import-content.sh
web/sites/default/settings.cloudgov.php

https://weathergov-design.app.cloud.gov/
https://github.com/weather-gov/weather.gov/actions/runs/8054624306
I walked @igorkorenfeld through administering this environment and the pitfalls. The main pitfall is: 
SAML is set up but until we add this domain to our cert, it will not work for this environment. Expect to get an error when attempting a SAML login. 
#822

create new design environment

---

tests/api/serve.js

-- What
We use dayjs' `startOf` feature to modify the date objects to start at the beginning of the hour if the following conditions are met:
1. We are in an hourly forecast file and are about to serve it;
2. The key of the current date value being parsed is either `startTime` or `endTime`

plz to let us have this

---

tests/api/data/testing/gridpoints/BMX/32,69.json
tests/api/data/testing/gridpoints/BMX/32,69/forecast.json
tests/api/data/testing/gridpoints/BMX/32,69/forecast/hourly.json
tests/api/data/testing/stations/KBHM/observations__limit=1.json
tests/api/data/testing/stations/KTCL/observations__limit=1.json
web/modules/weather_data/src/Service/Test/FormatDailyPeriod.php.test
web/modules/weather_data/src/Service/Test/GetCurrentConditionsFromGrid.php.test
web/modules/weather_data/src/Service/Test/GetHourlyForecast.php.test
web/modules/weather_data/src/Service/Test/GetIconTest.php.test
web/modules/weather_data/src/Service/WeatherDataService.php
web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
web/themes/new_weather_theme/templates/block/block--weathergov-daily-forecast.html.twig
web/themes/new_weather_theme/templates/partials/daily-forecast-list-item.html.twig

- adds a centralized thing for figuring out icons
- don't display icons if they're null
Closes #764

Don't show icons if they're null

---

README.md

The roadmap link in the readme was broken

Fix roadmap link in README

---

web/modules/weather_data/src/Service/HourlyForecastTrait.php
web/modules/weather_data/src/Service/Test/GetHourlyPrecipitation.php.test

Round precip values in the table to hundredths of an inch

---

docker-compose.yml

From MariaDB to MySQL. Whee!
closes #899
requires `make zap` to switch out the database

Switch our dev database to the same version used in the cloud

---

Makefile

Increase sleep duration to give more time between drupal rebuild and installation to fix failing MySQL connection

Increase sleep duration for pause recipe

---

web/themes/new_weather_theme/templates/partials/hourly-table.html.twig

This PR adds a check before each value in the the table and renders an "N/A" if the value is (strictly) null. 
To test I manually updated the Little Rock testing files to put in null and 0 values, but did not commit them. I could create a new set of files (in a different grid point) if that's helpful

Add check for values in hourly table

---

docs/dev/tests.md

Longer term, it might be useful to document the behaviors we're capturing in our tests to help the whole team see where we might need additional testing. This is a first pass at doing that, by documenting the block-based e2e tests that we've implemented.

List out existing block-based e2e tests

---

composer.json
composer.lock
web/config/sync/auto_entitylabel.settings.node.wfo_promo.yml
web/config/sync/core.base_field_override.node.wfo_promo.title.yml
web/config/sync/core.entity_form_display.node.wfo_promo.default.yml
web/config/sync/core.entity_view_display.node.wfo_promo.default.yml
web/config/sync/core.entity_view_mode.access_scheme.token.yml
web/config/sync/core.entity_view_mode.block.token.yml
web/config/sync/core.entity_view_mode.block_content.token.yml
web/config/sync/core.entity_view_mode.config_split.token.yml
web/config/sync/core.entity_view_mode.file.token.yml
web/config/sync/core.entity_view_mode.menu_link_content.token.yml
web/config/sync/core.entity_view_mode.node.token.yml
web/config/sync/core.entity_view_mode.path_alias.token.yml
web/config/sync/core.entity_view_mode.section_association.token.yml
web/config/sync/core.entity_view_mode.taxonomy_term.token.yml
web/config/sync/core.entity_view_mode.user.token.yml
web/config/sync/core.extension.yml
web/config/sync/editor.editor.basic_html.yml
web/config/sync/field.field.node.weather_story.body.yml
web/config/sync/field.field.node.wfo_promo.field_wfo.yml
web/config/sync/filter.format.basic_html.yml
web/themes/new_weather_theme/templates/block/block--weathergov-wfo-promo.html.twig

See #944 
* Weather story: "Body field includes a link that says “edit summary” which opens up a new field. This isn't a field that the component requires, so we can remove it to reduce confusion." I've removed this option. 
* WFO promo: Wfo name field/wfo field. I've combined these into one field named "WFO Name" that is a search for the wfo entity. 
* WFO promo: "When authored, the phone number field should include a tel tag so that users on a call-capable device are able to click to call" I've added a `tel:` a tag to this in the twig template
* WFO promo: "The icon for Twitter does not appear visible, even if the field for the URL is authored" I was not seeing this problem and had no issue generating the icon in the promos on location pages
* WFO promo: "WFO Page URL" I've just removed …

CMS UI tweaks for weather story and WFO promo

---

web/themes/new_weather_theme/templates/block/block--weathergov-current-conditions.html.twig
web/themes/new_weather_theme/templates/block/block--weathergov-hourly-precipitation.html.twig

Remove placeholder links

---

.gitignore
composer.json
web/robots.txt

Fixes #1049 
We are overriding the scaffold default. This works in design: https://weathergov-design.app.cloud.gov/robots.txt

disallow all in robots.txt

---

spatial-data/lib/meta.js
spatial-data/load-shapefiles.js
spatial-data/sources/zones.js

Adds forecast and fire weather zones to our spatial database

Load forecast and fire weather zones

---

web/themes/new_weather_theme/templates/block/block--weathergov-dynamic-safety-information.html.twig

Fixes a bug that prevents dynamic safety info from rendering

Fix template

---

.github/workflows/code-standards.yaml
scripts/load-spatial-data.sh

fix annoying prod/beta syntax misalignment in spatial script

---

tests/e2e/cypress/e2e/alerts.cy.js
web/themes/new_weather_theme/templates/block/block--weathergov-local-alerts.html.twig

Addresses #1075 and makes all alert accordions open by default.
I've also added e2e tests for this

All alerts open by default

---

web/themes/new_weather_theme/assets/js/components/combo-box.js
web/themes/new_weather_theme/new_weather_theme.libraries.yml
web/themes/new_weather_theme/templates/block/block--weathergov-location-search.html.twig

Deals with #1059 where there wasn't a matching element with aria-descrption text.
I _think_ this was pretty straightforward? But am slightly suspicious.

Combo box aria description

---

composer.lock

Drupal core was updated May 1st to 10.2.6, so updating that. Also updating some packages.

update drupal core and other modules

---

web/themes/new_weather_theme/templates/field/field--node--field-facebook-url--wfo-promo.html.twig
web/themes/new_weather_theme/templates/field/field--node--field-twitter-url--wfo-promo.html.twig
web/themes/new_weather_theme/templates/field/field--node--field-youtube-url--wfo-promo.html.twig
web/themes/new_weather_theme/templates/partials/external-link-decoration.html.twig

* visually identifies Facebook, YouTube, and X as external links using the USWDS "launch" icon
* audibly identifies Facebook, YouTube, and X as external links using sr-only text
A small piece of #336

Add external link decoration to social media links

---

web/themes/new_weather_theme/assets/js/locationSearch.js

Just what it says on the tin. Basically moves the call to show the loader to the click handler rather then the form submit.
- closes #1301

Show loading indicator on click of "use my location" button

---

web/config/cloudgov/views.view.samlauth_map.yml
web/config/sync/system.action.user_add_role_action.user_admin.yml
web/config/sync/system.action.user_remove_role_action.user_admin.yml
web/config/sync/user.role.administrator.yml
web/config/sync/user.role.content_admin.yml
web/config/sync/user.role.user_admin.yml

Fixes #1216 with initial settings for "user admin" role.

add new user admin role, rename system admin to owner

---

.github/actions/setup-site/action.yml

I think we just forgot to update how the hash for the database build is formed .

Fix CI databse cache / building issue

---

docs/dev/location.md

Add notes on how we do location and why

Notes on location

---

web/modules/weather_routes/src/Controller/WeatherInfoController.php

Rebase / merge conflicts in a previous PR of mine accidentally reset this file to an older version. We need this latest version for WFO pages to load properly.

Restoring latest version of WeatherInfoController

---

.github/workflows/code-standards.yaml

Don't merge test reports on doc-only PRs

---

.github/workflows/code-standards.yaml
docs/dev/index.md
docs/dev/review-standards.md
docs/dev/testing.md

Update developer docs for security review, dependabot process, and playwright end-to-end testing (which might involve `WX_NOW_TIMESTAMP`).
Nothing else; please read the documentation and make sure it makes sense/reads well.

update developer documentation

---

.github/actions/build-drupal-image/action.yml
Dockerfile.dev
Makefile
docker-compose.yml

Attempts to fix internal docker permissions with respect to Drupal.
I suggest doing a clean git clone, checking out this branch, and then building. Otherwise, you might need to `git clean -fxd` to remove extant files with mangled permissions. 
To test: `make php-format` or try to upload a file. Shouldn't be any weird permission issues.

docker: set www-data uid/gid to host's uid/gid

---

.github/ISSUE_TEMPLATE/adr-template.yaml

fix misspellings in ADR issue template

---

web/themes/new_weather_theme/new_weather_theme.libraries.yml

Update styles version to bust caches

---

web/modules/weather_blocks/src/Plugin/Block/Test/Base.php.test
web/modules/weather_blocks/src/Plugin/Block/Test/WeatherBlockBase.php.test

After removing the PHP DataLayer, the base block got a lot simpler, but I forgot to update all of the tests to remove the tests associated with the removed complexity. This PR fixes those tests up.

[Interop layer] Fix PHP unit test bug

---

api-interop-layer/data/alerts/index.js
api-interop-layer/data/alerts/index.test.js
api-interop-layer/data/db.js
api-interop-layer/mocha.js
api-interop-layer/package.json
api-interop-layer/util/fetch.test.js

[Interop Layer] Test that only land alerts are returned

---

api-interop-layer/data/alerts/index.js
api-interop-layer/data/alerts/index.test.js

Adds tests related to computing an alerts finishing time.
- closes #1597

[Interop layer] Add tests for alert finishing time

---

api-interop-layer/data/alerts/parse/duration.js
api-interop-layer/data/alerts/parse/duration.test.js

[Interop layer] Add tests for alert duration text

---

api-interop-layer/data/alerts/index.test.js

Adds tests to confirm that the highest alert level is correctly computed for a given set of alerts.
- Closes #1599

[Interop layer] Add tests for highest alert level for a set of alerts

---

api-interop-layer/data/satellite.test.js
api-interop-layer/package.json
api-interop-layer/util/monitoring/index.js

[Interop layer] Add satellite metadata tests

---

manifests/manifest-james.yaml

Sandbox env for `james` env. Exactly the same as the others (modulo the name).

sandbox manifest for james env

---

web/themes/new_weather_theme/templates/block/block--weathergov-wfo-promo.html.twig

This small PR updates the link color for the WFO promo office name to match other links styles.

Change WFO promo link to usa-link

---

docker-compose.test.yml
docker-compose.yml
web/modules/weather_data/weather_data.module

[Interop layer] Have Drupal get the interop URL from env var

---

api-interop-layer/data/obs/index.js
api-interop-layer/data/obs/index.test.js

Adds tests for the observations module.
- closes #1606
- closes #1607

[Interop layer] Add observations tests

---

web/themes/new_weather_theme/assets/js/charts/hourly-wind.js
web/themes/new_weather_theme/new_weather_theme.libraries.yml

Fix from #1799 
The angle we get represents where the wind is blowing _from_, so we simply need to add 180 degrees to the arrow's rotation to get the right vector

Fix wind direction arrows

---

cronish.sh
scripts/bootstrap.sh
scripts/create-cloudgov-env.sh
scripts/import-content.sh
scripts/load-spatial-data.sh
scripts/remove-cloudgov-env.sh
scripts/rotate-gh-deploy-keys.sh

Run `shellcheck` and remove references to CISA
Closes https://github.com/weather-gov/weather.gov/issues/1809
Nada

scripts: fixed warnings from shellcheck

---

.eslintrc.js
.github/actions/javascript-lint/action.yml
api-interop-layer/data/forecast/quantitativePrecipitation.test.js
api-interop-layer/data/obs/index.js
api-interop-layer/mocha.js
api-interop-layer/util/convert.js
api-interop-layer/util/icon.legacyMapping.test.js
api-interop-layer/util/monitoring/index.js
package-lock.json
package.json
scripts/compile-svg-sprite.js
spatial-data/trim-geonames-csv.js
tests/api/main.js
web/themes/new_weather_theme/gulpfile.js

... at least, for the `api-interop-layer` branch.

eslint all the things

---

web/modules/weather_blocks/weather_blocks.module
web/themes/new_weather_theme/templates/partials/satellite.html.twig

Add satellite video

---

.github/workflows/deploy-sandbox.yaml

- Add `james` as an option to the deploy action
- Add `ALLOWED_IP_ADDRESSES` for proxy configuration

update deploy-sandbox action

---

api-interop-layer/data/forecast/quantitativePrecipitation.test.js

Turns out we already did #1834, so this adds tests to show that.
- closes #1834

Add tests to show we handle QPF across days

---

api-interop-layer/data/alerts/kinds.js

Sister PR to #1801 and finishes implementing changes from #1697 
This mirrors the changes in the PHP side from #1801

[HOLD UNTIL OCT 1] WWA updates for interop layer

---

api-interop-layer/data/alerts/kinds.js
api-interop-layer/package-lock.json

- eslint fixes
- package updates to address security vulns

fix eslint/npm audit errors for api-interop-layer

---

api-interop-layer/data/satellite.js
api-interop-layer/data/satellite.test.js
api-interop-layer/util/monitoring/index.js
web/themes/new_weather_theme/templates/partials/satellite.html.twig

[Interop layer] Add satellite video to metadata

---

api-interop-layer/data/forecast/hourly.js
api-interop-layer/data/forecast/hourly.test.js
api-interop-layer/data/forecast/index.js
tests/e2e/cypress/e2e/hourly-forecast-table.cy.js

Implements #1605 
Minor refactoring to the underlying code so that the ACs are met and also so parts are easier to test.

Interop hourly data tests

---

tests/api/data/testing/gridpoints/LZK/83,73.json
tests/api/data/testing/points/34.749,-92.275.json
tests/playwright/e2e/qpf-table.spec.js
web/themes/new_weather_theme/assets/js/charts/qpf.js
web/themes/new_weather_theme/new_weather_theme.libraries.yml
web/themes/new_weather_theme/templates/partials/precip-table.html.twig

- Just what it says on the tin
- Updates the bundle metadata so it's more descriptive of the available test data
- Adds tests to capture this behavior of the QPF table

Fix: QPF table should say "rain" if there is no ice or snow, instead of "water"

---

api-interop-layer/data/forecast/index.js
api-interop-layer/data/forecast/quantitativePrecipitation.test.js
api-interop-layer/interop-layer.schema.json
web/themes/new_weather_theme/assets/js/charts/hourly-wind.js
web/themes/new_weather_theme/templates/partials/daily-forecast-list-item.html.twig
web/themes/new_weather_theme/templates/partials/hourly-charts.html.twig
web/themes/new_weather_theme/templates/partials/hourly-table.html.twig
web/themes/new_weather_theme/templates/partials/precip-table.html.twig

This PR fixes the data expectations between the interop layer and the charts.

[Interop layer] Fix charts

---

.github/workflows/code-standards.yaml
api-interop-layer/data/obs/index.test.js
api-interop-layer/package.json
api-interop-layer/util/convert.js
api-interop-layer/util/fetch.js
api-interop-layer/util/fetch.test.js

- adds a few tests for some of the utility modules
- updates CI/CD to capture interop tests coverage and merge with Drupal coverage to give us an overall number

[Interop layer] Utility tests and add code coverage to CI/CD

---

api-interop-layer/data/alerts/parse/duration.js
api-interop-layer/data/alerts/parse/duration.test.js

Interop layer companion for #1934

[Interop layer] Don't show timezone on alert duration text

---

web/themes/new_weather_theme/assets/manifest.json

Adds "beta" to app name for clarity and emphasizes url

Update app name

---

web/themes/new_weather_theme/templates/layout/html--node--preview.html.twig
web/themes/new_weather_theme/templates/layout/html.html.twig
web/themes/new_weather_theme/templates/layout/page--point.html.twig
web/themes/new_weather_theme/templates/partials/daily-forecast-list-item.html.twig
web/themes/new_weather_theme/templates/partials/hourly-table.html.twig
web/themes/new_weather_theme/templates/partials/radar.html.twig
web/themes/new_weather_theme/templates/point/observations.html.twig

A place to collect small fixes related to the interop layer switch

Interop fixups

---

api-interop-layer/util/monitoring/newRelic.js

Fix reference to `newrelic.recordLogEvent`

---

.eslintrc.js
api-interop-layer/data/alerts/backgroundUpdateTask.js
api-interop-layer/data/alerts/backgroundUpdateTask.test.js
api-interop-layer/data/alerts/geometry.js
api-interop-layer/data/alerts/geometry.test.js
api-interop-layer/data/alerts/index.js
api-interop-layer/data/alerts/index.test.js
api-interop-layer/main.js
api-interop-layer/package-lock.json
api-interop-layer/package.json
docs/dev/contributed-modules.md

- Moves alert updating and processing into a background thread
- Adds alert hashing to uniquely identify alerts
- Only processes alerts from the API if it has not processed them before
- Removes locally-stored alerts if they are no longer in the API data
- Moves some heavy spatial processing into code that is faster than MySQL
The code that gets a list of alerts for a location goes from about 1,000 milliseconds down to around 300 milliseconds (with around 30 active alerts), and should result in a quicker user experience.
---
- fixes #1977
- fixes #1976
- closes #1881

Background alert processing

---

api-interop-layer/data/alerts/backgroundUpdateTask.test.js

In #2002, we modified the alert background processing to send log messages into the main process so they could be logged to NewRelic, but we failed to update our tests to account for log messages. As a result, our tests that depended on the ordering of messages began to fail.
This PR modifies the behavior of the tests so instead of depending strictly on the order of messages, it filters messages by action type and uses that instead. This should be more resilient to future changes. 
This should be merged prior to making interop tests required so it doesn't block other PRs.

Fix interop layer alert tests

---

web/themes/new_weather_theme/assets/js/radar.js

- closes #1961
@sarahmhgov Do you have a preference between these two? This PR does two zoom levels, but it's literally changing a '6' to a '7' if one zoom level is better, so whichever is cool with me!

Zoom out radar more at default

---

docs/dev/intercepting-the-api.md
tests/api/config.js
tests/api/index.mustache
tests/api/main.js
tests/api/package-lock.json
tests/api/package.json
tests/api/products.js
tests/api/proxy.js
tests/api/save.js

- Instead of manually building up a UI for the proxy by pushing lines of HTML to an array and then dumping them into the response, this PR adds mustache and a template. It's a lot easier to read!
- While I was doing that, I styled the thing up to be nicer to look at.
- I added a button for recording a new bundle. This button is attached to a text box. In that text box, you'll put a URL to a point location page. Behind the scenes, the proxy will parse that URL to find the lat/lon for the location page, and then it'll bundle that up. The new bundle's path will be the current Javascript timestamp (Unix epoch, in milliseconds)
- I also added a button to add a single point to an existing bundle. The main difference between the two (other than where on disk they store their files) is that …

fix up the proxy thingy

---

.github/actions/set-library-versions/action.yml

If the library file is empty, don't do anything with it.

Fix library update script

---

manifests/manifest-design.yaml
manifests/manifest-eric.yaml
manifests/manifest-greg.yaml
manifests/manifest-james.yaml
manifests/manifest-staging.yaml
manifests/manifest.template.yaml

Does what it says on the tin.
We'll have to add the env var similarly for beta once the appropriate time comes.

configure environments for api interop layer

---

manifests/manifest-beta.yaml

Sets up our production api interop layer :tada:

beta: deploy interop layer

---

.github/workflows/deploy-beta.yaml

Fix interop deploy to beta

---

docker-compose.test.yml

Let's not reuse the same network for our dev/test environments -- this causes errors.

set up a separate network for the test env

---

web/config/sync/core.entity_form_display.node.wfo_pdf_upload.default.yml
web/config/sync/core.entity_view_display.node.wfo_pdf_upload.default.yml
web/config/sync/core.entity_view_display.node.wfo_pdf_upload.teaser.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_pdf_description.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_pdf_endtime.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_pdf_front_page.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_pdf_order.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_pdf_starttime.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_pdf_title.yml
web/config/sync/field.field.node.wfo_pdf_upload.field_wfo_sitrep.yml
web/config/sync/field.storage.node.field_pdf_description.yml
web/config/sync/field.storage.node.field_pdf_endtime.yml
web/config/sync/field.storage.node.field_pdf_front_page.yml
web/config/sync/field.storage.node.field_pdf_order.yml
web/config/sync/field.storage.node.field_pdf_starttime.yml
web/config/sync/field.storage.node.field_pdf_title.yml
web/modules/weather_cms/weather_cms.module

Adds optional attributes for PDF uploads. Also overwrites previous PDF files (similar to weather story uploads).
Closes https://github.com/weather-gov/weather.gov/issues/1887

dss builder pdf uploads: add optional attrs

---

api-interop-layer/ecosystem.config.cjs

Updates config to watch for _all_ js file changes
Was previously not updating on code changes, because it was only watching js files at the root level

PM2 watch config tweak

---

Dockerfile.uswds
Dockerfile.utility-node

Fixes typos in docker definitions.

fix zscaler typos for uswds/node docker

---

web/modules/weather_i18n/translations/en.po
web/themes/new_weather_theme/templates/partials/hourly-charts.html.twig
web/themes/new_weather_theme/templates/partials/hourly-table.html.twig
web/themes/new_weather_theme/templates/partials/precip.html.twig

Fixes missing precipitation chart and unneeded legend on the table view.
https://vlab.noaa.gov/gitlab-licensed/NWS/Systems/DIS/Weather.gov-2.0/-/issues/43 🔒

Consolidate precip data in one file

---

web/config/sync/language.entity.es.yml
web/config/sync/language.entity.und.yml
web/config/sync/language.entity.zxx.yml
web/config/sync/language.negotiation.yml
web/modules/weather_i18n/translations/es.po

Implements a bare-bones static Spanish `es.po` file with no dynamic placeholders.
Some of the strings in the `es.po` file need removed. Lots needed added. And dynamic placeholders aren't there yet--everything is static text.

Add Spanish localization

---

web/modules/weather_blocks/src/Plugin/Block/WeatherStoryImageBlock.php
web/modules/weather_cms/weather_cms.module

Tweaks for DSS builder integration; specifically, fixes [!56](https://vlab.noaa.gov/gitlab-licensed/NWS/Systems/DIS/Weather.gov-2.0/-/issues/56) (Weather story uploads have extra whitespace in titles) and [!57](https://vlab.noaa.gov/gitlab-licensed/NWS/Systems/DIS/Weather.gov-2.0/-/issues/57) (Weather story image URLs not updating for display)
Nada

dss builder tweaks: trim desc and set file uri

---

web/themes/new_weather_theme/templates/block/block--weathergov-weather-story-image.html.twig

Fixes `Expected name or number, got value "(" of type punctuation."`.
I'm not sure how to test this on my local env.

Fix syntax error in translation call

---

docs/dev/json-api-upload-weather-story-example.py
web/themes/new_weather_theme/templates/block/block--weathergov-weather-story-image.html.twig

Link was broken due to syntax error.
I wasn't able to get weather stories on my local, so I tested the syntax on the AFD link on `page--point.twig.html`.

Fix broken link to WFO on weather story

---

docs/dev/json-api-upload-weather-story-example.py
web/modules/weather_blocks/src/Plugin/Block/Test/WeatherStoryImageBlock.php.test
web/modules/weather_blocks/src/Plugin/Block/WeatherStoryImageBlock.php
web/modules/weather_i18n/translations/en.po
web/themes/new_weather_theme/templates/block/block--weathergov-weather-story-image.html.twig

Uses the starttime attribute rather than when Drupal created the weather story. Tests for `0` because starttime is sometimes `0`.

Fix weather story timestamps
